<?php
declare(strict_types=1);
require __DIR__.'/../src/bootstrap.php'; require __DIR__.'/../src/LeadService.php'; require __DIR__.'/../src/SdrService.php'; require __DIR__.'/../src/CommercialService.php'; require __DIR__.'/../src/OperationsService.php'; require __DIR__.'/../src/FlowService.php'; require __DIR__.'/../src/ConversationService.php'; require __DIR__.'/../src/PropertyService.php'; require __DIR__.'/../src/SettingsService.php'; require __DIR__.'/../src/SiteService.php'; require __DIR__.'/../src/CreditService.php'; require __DIR__.'/../src/SimplePdf.php'; require __DIR__.'/../src/ContractTemplates.php'; require __DIR__.'/../src/DocumensoClient.php'; require __DIR__.'/../src/ContractService.php';
header('Access-Control-Allow-Origin: '.(getenv('FRONTEND_URL')?:'http://localhost:5173')); header('Access-Control-Allow-Headers: Content-Type, Authorization, X-Webhook-Token'); header('Access-Control-Allow-Methods: GET,POST,PUT,DELETE,OPTIONS'); if($_SERVER['REQUEST_METHOD']==='OPTIONS')exit;
$path=parse_url($_SERVER['REQUEST_URI'],PHP_URL_PATH);$method=$_SERVER['REQUEST_METHOD'];
try {
 if($path==='/api/health')respond(['status'=>'ok']);
 $svc=new LeadService(db());
 $sdr=new SdrService(db());
 $commercial=new CommercialService(db());
 $ops=new OperationsService(db());
 $flows=new FlowService(db(),$svc);
 $conversations=new ConversationService(db());
 $properties=new PropertyService(db(),$ops,__DIR__.'/uploads/properties',rtrim(getenv('APP_URL')?:'','/'));
 $settings=new SettingsService(db());
 $credit=new CreditService(db(),$ops,$svc);
 $CREDIT=['admin','manager','broker','analyst'];
 $contracts=new ContractService(db(),$ops,$settings,$commercial,DocumensoClient::fromEnv());
 $pdfOut=function(string $file,string $name,bool $inline){if(!is_file($file))throw new RuntimeException('Arquivo não encontrado no armazenamento.');header('Content-Type: application/pdf');header('Content-Length: '.filesize($file));header('Content-Disposition: '.($inline?'inline':'attachment').'; filename="'.rawurlencode($name).'"');header('X-Content-Type-Options: nosniff');header('Cache-Control: private, no-store');readfile($file);exit;};
 if($path==='/api/webhooks/documenso'&&$method==='POST'){$expected=(string)getenv('DOCUMENSO_WEBHOOK_SECRET');if($expected==='')respond(['message'=>'Webhook do Documenso não configurado (DOCUMENSO_WEBHOOK_SECRET).'],503);if(!hash_equals($expected,(string)($_SERVER['HTTP_X_DOCUMENSO_SECRET']??'')))respond(['message'=>'Segredo inválido.'],401);respond(['received'=>true,'matched'=>$contracts->webhook(json_input())]);}
 if($path==='/api/contracts'&&$method==='GET'){$u=auth(['admin','manager','broker']);respond($contracts->list($u,$_GET));}
 if($path==='/api/contracts'&&$method==='POST'){$u=auth(['admin','manager','broker']);$d=json_input();validate_required($d,['credit_application_id']);respond(['data'=>$contracts->createFromCredit($d['credit_application_id'],$u)],201);}
 if(preg_match('#^/api/contracts/([a-f0-9]{32})$#',$path,$m)&&$method==='GET'){$u=auth(['admin','manager','broker']);respond(['data'=>$contracts->get($m[1],$u)]);}
 if(preg_match('#^/api/contracts/([a-f0-9]{32})$#',$path,$m)&&$method==='PUT'){$u=auth(['admin','manager','broker']);respond(['data'=>$contracts->update($m[1],json_input(),$u)]);}
 if(preg_match('#^/api/contracts/([a-f0-9]{32})/(send|refresh)$#',$path,$m)&&$method==='POST'){$u=auth(['admin','manager','broker']);respond(['data'=>$m[2]==='send'?$contracts->send($m[1],$u):$contracts->refresh($m[1],$u)]);}
 if(preg_match('#^/api/contracts/([a-f0-9]{32})/cancel$#',$path,$m)&&$method==='POST'){$u=auth(['admin','manager','broker']);$d=json_input();respond(['data'=>$contracts->cancel($m[1],(string)($d['reason']??''),$u)]);}
 if(preg_match('#^/api/contracts/([a-f0-9]{32})/signed$#',$path,$m)&&$method==='POST'){$u=auth(['admin','manager','broker']);if(empty($_FILES['file']))throw new InvalidArgumentException('Anexe o PDF assinado.');respond(['data'=>$contracts->uploadSigned($m[1],$_FILES['file'],$u)]);}
 if(preg_match('#^/api/contracts/([a-f0-9]{32})/pdf$#',$path,$m)&&$method==='GET'){$u=auth(['admin','manager','broker']);[$file,$name]=$contracts->file($m[1],$u,($_GET['signed']??'')==='1');$pdfOut($file,$name,($_GET['inline']??'')==='1');}
 if($path==='/api/contract-templates'&&$method==='GET'){auth(['admin','manager']);respond($contracts->templates());}
 if(preg_match('#^/api/contract-templates/(sale_cash|sale_financed|sale_down_payment|lease)$#',$path,$m)&&$method==='PUT'){$u=auth(['admin']);$d=json_input();respond($contracts->saveTemplate($m[1],array_key_exists('body',$d)&&$d['body']!==null?(string)$d['body']:null,$u));}
 if(preg_match('#^/api/contract-templates/(sale_cash|sale_financed|sale_down_payment|lease)/preview$#',$path,$m)&&$method==='POST'){auth(['admin','manager']);$d=json_input();$pdf=$contracts->preview($m[1],isset($d['body'])?(string)$d['body']:null);header('Content-Type: application/pdf');header('Content-Disposition: inline; filename="previa-'.$m[1].'.pdf"');header('Cache-Control: no-store');echo $pdf;exit;}
 if($path==='/api/credit'&&$method==='GET'){$u=auth($CREDIT);respond($credit->list($u,$_GET));}
 if($path==='/api/credit'&&$method==='POST'){$u=auth(['admin','manager','broker']);respond(['data'=>$credit->create(json_input(),$u)],201);}
 if(preg_match('#^/api/credit/([a-f0-9]{32})$#',$path,$m)&&$method==='GET'){$u=auth($CREDIT);respond(['data'=>$credit->get($m[1],$u)]);}
 if(preg_match('#^/api/credit/([a-f0-9]{32})$#',$path,$m)&&$method==='PUT'){$u=auth(['admin','manager','broker']);respond(['data'=>$credit->update($m[1],json_input(),$u)]);}
 if(preg_match('#^/api/credit/([a-f0-9]{32})/(submit|claim)$#',$path,$m)&&$method==='POST'){$u=auth($CREDIT);respond(['data'=>$m[2]==='submit'?$credit->submit($m[1],$u):$credit->claim($m[1],$u)]);}
 if(preg_match('#^/api/credit/([a-f0-9]{32})/decision$#',$path,$m)&&$method==='POST'){$u=auth(['admin','manager','analyst']);respond(['data'=>$credit->decide($m[1],json_input(),$u)]);}
 if(preg_match('#^/api/credit/([a-f0-9]{32})/cancel$#',$path,$m)&&$method==='POST'){$u=auth(['admin','manager','broker']);$d=json_input();respond(['data'=>$credit->cancel($m[1],(string)($d['reason']??''),$u)]);}
 if(preg_match('#^/api/credit/([a-f0-9]{32})/documents$#',$path,$m)&&$method==='POST'){$u=auth($CREDIT);if(empty($_FILES['file']))throw new InvalidArgumentException('Nenhum arquivo enviado.');respond(['data'=>$credit->addDocument($m[1],$_FILES['file'],(string)($_POST['kind']??''),$u)],201);}
 if(preg_match('#^/api/credit/([a-f0-9]{32})/documents/([a-f0-9]{32})$#',$path,$m)&&$method==='DELETE'){$u=auth(['admin','manager','broker']);respond(['data'=>$credit->removeDocument($m[1],$m[2],$u)]);}
 if(preg_match('#^/api/credit/([a-f0-9]{32})/documents/([a-f0-9]{32})$#',$path,$m)&&$method==='GET'){$u=auth($CREDIT);$doc=$credit->document($m[1],$m[2],$u);$file=private_storage().'/'.$doc['storage_name'];if(!is_file($file))throw new RuntimeException('Arquivo não encontrado no armazenamento.');header('Content-Type: '.$doc['mime_type']);header('Content-Length: '.filesize($file));header('Content-Disposition: '.(($_GET['inline']??'')==='1'?'inline':'attachment').'; filename="'.rawurlencode($doc['original_name']).'"');header('X-Content-Type-Options: nosniff');header('Cache-Control: private, no-store');readfile($file);exit;}
 $site=new SiteService(db(),$svc,$settings,rtrim(getenv('APP_URL')?:'','/'));
 if($path==='/api/public/site'&&$method==='GET')respond(['data'=>$site->info()]);
 if($path==='/api/public/filters'&&$method==='GET')respond(['data'=>$site->filters()]);
 if($path==='/api/public/properties'&&$method==='GET')respond($site->list($_GET));
 if(preg_match('#^/api/public/properties/([a-f0-9]{32})$#',$path,$m)&&$method==='GET')respond(['data'=>$site->get($m[1])]);
 if($path==='/api/public/leads'&&$method==='POST')respond(['data'=>$site->lead(json_input(),client_ip())],201);
 if($path==='/api/public/chat'&&$method==='POST')respond(['data'=>$site->chatStart(json_input(),client_ip())],201);
 if(preg_match('#^/api/public/chat/([a-f0-9]{48})$#',$path,$m)&&$method==='GET')respond(['data'=>$site->chatPoll($m[1],client_ip())]);
 if(preg_match('#^/api/public/chat/([a-f0-9]{48})/messages$#',$path,$m)&&$method==='POST'){$d=json_input();respond(['data'=>$site->chatSend($m[1],(string)($d['message']??''),client_ip())],201);}
 if(preg_match('#^/api/settings/(company|site|contracts)$#',$path,$m)&&$method==='GET'){auth(['admin','manager']);respond(['data'=>$settings->get($m[1])]);}
 if(preg_match('#^/api/settings/(company|site|contracts)$#',$path,$m)&&$method==='PUT'){$u=auth(['admin']);$data=$settings->put($m[1],json_input(),$u);$ops->audit($u['id'],'settings_updated','settings',str_pad($m[1],32,'_'),'Configurações atualizadas: '.$m[1]);respond(['data'=>$data]);}
 if($path==='/api/login'&&$method==='POST'){$d=json_input();validate_required($d,['email','password']);$q=db()->prepare('SELECT * FROM users WHERE email=? AND active=1');$q->execute([$d['email']]);$u=$q->fetch();if(!$u||!password_verify($d['password'],$u['password_hash']))respond(['message'=>'E-mail ou senha inválidos.'],401);$token=bin2hex(random_bytes(32));$q=db()->prepare('INSERT INTO auth_tokens(id,user_id,token_hash,expires_at) VALUES(?,?,?,?)');$q->execute([uid(),$u['id'],hash('sha256',$token),date('Y-m-d H:i:s',time()+28800)]);respond(['token'=>$token,'user'=>array_intersect_key($u,array_flip(['id','name','email','role']))]);}
 if($path==='/api/logout'&&$method==='POST'){$u=auth();$q=db()->prepare('DELETE FROM auth_tokens WHERE token_hash=?');$q->execute([hash('sha256',(string)bearer())]);respond(['message'=>'Sessão encerrada.']);}
 if($path==='/api/me')respond(['user'=>auth()]);
 if($path==='/api/sources'){$u=auth();respond(['data'=>db()->query('SELECT * FROM lead_sources ORDER BY name')->fetchAll()]);}
 if($path==='/api/integrations'){$u=auth(['admin','manager']);$rows=db()->query("SELECT id,code,name,purpose,status,implementation_status,provider,config,requirements,last_event_at,last_test_at,last_test_result,(secret_ciphertext IS NOT NULL) secret_saved FROM integration_connectors ORDER BY name")->fetchAll();foreach($rows as &$r){$q=db()->prepare('SELECT level,message,created_at FROM integration_logs WHERE connector_id=? ORDER BY created_at DESC LIMIT 10');$q->execute([$r['id']]);$r['logs']=$q->fetchAll();}respond(['data'=>$rows]);}
 if(preg_match('#^/api/integrations/([a-f0-9]{32})$#',$path,$m)&&$method==='PUT'){$u=auth(['admin']);$d=json_input();$config=$d['config']??[];$secret=null;if(!empty($d['secret'])){$key=getenv('APP_ENCRYPTION_KEY')?:'';if(strlen($key)<32)throw new RuntimeException('Configure APP_ENCRYPTION_KEY com ao menos 32 caracteres.');$nonce=random_bytes(SODIUM_CRYPTO_SECRETBOX_NONCEBYTES);$secret=base64_encode($nonce.sodium_crypto_secretbox(json_encode($d['secret']),$nonce,hash('sha256',$key,true)));}db()->prepare('UPDATE integration_connectors SET config=?,secret_ciphertext=COALESCE(?,secret_ciphertext),status=? WHERE id=?')->execute([json_encode($config),$secret,$d['status']??'ready_for_test',$m[1]]);respond(['message'=>'Configuração salva sem exposição de segredos.']);}
 if(preg_match('#^/api/integrations/([a-f0-9]{32})/test$#',$path,$m)&&$method==='POST'){$u=auth(['admin']);$q=db()->prepare('SELECT * FROM integration_connectors WHERE id=?');$q->execute([$m[1]]);$c=$q->fetch();if(!$c)throw new RuntimeException('Conector não encontrado.');$local=in_array($c['provider'],['simulator','webhook'],true);$result=$local?'Teste local concluído; nenhuma plataforma externa foi contatada.':'Configuração registrada; validação real depende das credenciais e da plataforma.';$status=$local?'ready_for_test':$c['status'];db()->prepare('UPDATE integration_connectors SET last_test_at=CURRENT_TIMESTAMP,last_test_result=?,status=? WHERE id=?')->execute([$result,$status,$c['id']]);db()->prepare("INSERT INTO integration_logs(id,connector_id,level,message) VALUES(?,?, 'info',?)")->execute([uid(),$c['id'],$result]);respond(['message'=>$result,'real_platform_validated'=>false]);}
 if($path==='/api/integrations/simulate'&&$method==='POST'){$u=auth(['admin','manager']);$d=json_input();validate_required($d,['channel','external_id','name','interest_type']);$sourceCode=match($d['channel']){'whatsapp_simulator','whatsapp_pam','whatsapp_meta'=>'whatsapp','site_chat'=>'site','quintoandar'=>'quintoandar','voip'=>'partner','power_bi'=>throw new InvalidArgumentException('Power BI é um conector de saída.'),default=>$d['channel']};$q=db()->prepare('SELECT id FROM lead_sources WHERE code=?');$q->execute([$sourceCode]);$source=$q->fetchColumn();if(!$source)throw new InvalidArgumentException('Canal sem origem cadastrada.');$event=uid();$payload=$d;foreach(['password','token','secret'] as $k)if(isset($payload[$k]))$payload[$k]='[REDACTED]';db()->prepare("INSERT INTO integration_events(id,source_id,external_id,payload,payload_hash,status) VALUES(?,?,?,?,?,'received')")->execute([$event,$source,$d['external_id'],json_encode($payload),hash('sha256',json_encode($d))]);try{$d['source_id']=$source;$lead=$svc->create($d,$u['id']);db()->prepare("UPDATE integration_events SET status='processed',result_message='Evento simulado processado',processed_at=CURRENT_TIMESTAMP WHERE id=?")->execute([$event]);db()->prepare('UPDATE integration_connectors SET last_event_at=CURRENT_TIMESTAMP WHERE code=?')->execute([$d['channel']]);respond(['event_id'=>$event,'lead_id'=>$lead['id'],'simulated'=>true],201);}catch(Throwable $e){db()->prepare("UPDATE integration_events SET status='duplicate',result_message=? WHERE id=?")->execute([$e->getMessage(),$event]);throw $e;}}
 if($path==='/api/flows'&&$method==='GET'){$u=auth(['admin','manager']);respond(['data'=>db()->query('SELECT f.*,v.graph,v.validation_errors,v.version_number FROM automation_flows f LEFT JOIN flow_versions v ON v.id=f.draft_version_id ORDER BY f.updated_at DESC')->fetchAll()]);}
 if($path==='/api/flows'&&$method==='POST'){$u=auth(['admin','manager']);$d=json_input();validate_required($d,['name']);respond(['data'=>$flows->save($d['id']??null,$d['name'],$d['graph']??['nodes'=>[]],$u)],201);}
 if(preg_match('#^/api/flows/([a-f0-9]{32})/publish$#',$path,$m)&&$method==='POST'){$u=auth(['admin','manager']);$flows->publish($m[1],$u);respond(['message'=>'Versão publicada.']);}
 if($path==='/api/simulator/message'&&$method==='POST'){$u=auth(['admin','manager']);$d=json_input();validate_required($d,['flow_id','conversation_id','message']);respond(['data'=>$flows->message($d['flow_id'],$d['conversation_id'],$d['message'],!empty($d['integrated']),$u)]);}
 if($path==='/api/simulator/reset'&&$method==='POST'){$u=auth(['admin','manager']);$d=json_input();db()->prepare("DELETE FROM conversations WHERE provider='simulator' AND external_id=?")->execute([$d['conversation_id']??'']);respond(['message'=>'Simulação reiniciada.']);}
 if($path==='/api/conversations'&&$method==='GET'){$u=auth(['admin','manager','sdr','broker']);$rows=$conversations->list($u);$pending=count(array_filter($rows,fn($r)=>$r['status']==='human'));respond(['data'=>$rows,'pending'=>$pending]);}
 if(preg_match('#^/api/conversations/([a-f0-9]{32})$#',$path,$m)&&$method==='GET'){$u=auth(['admin','manager','sdr','broker']);respond(['data'=>$conversations->get($m[1],$u)]);}
 if(preg_match('#^/api/conversations/([a-f0-9]{32})/assign$#',$path,$m)&&$method==='POST'){$u=auth(['admin','manager','sdr','broker']);respond(['data'=>$conversations->assign($m[1],$u)]);}
 if(preg_match('#^/api/conversations/([a-f0-9]{32})/reply$#',$path,$m)&&$method==='POST'){$u=auth(['admin','manager','sdr','broker']);$d=json_input();validate_required($d,['message']);respond(['data'=>$conversations->reply($m[1],$d['message'],$u)]);}
 if(preg_match('#^/api/conversations/([a-f0-9]{32})/resolve$#',$path,$m)&&$method==='POST'){$u=auth(['admin','manager','sdr','broker']);respond(['data'=>$conversations->resolve($m[1],$u)]);}
 if($path==='/api/internal/messages'&&$method==='POST'){$provided=$_SERVER['HTTP_X_CONNECTOR_TOKEN']??'';$expected=getenv('CONNECTOR_INTERNAL_TOKEN')?:'';if(!$expected||!hash_equals($expected,$provided))respond(['message'=>'Conector não autorizado.'],401);$d=json_input();validate_required($d,['provider','external_message_id','conversation_id','message']);$q=db()->prepare('SELECT id FROM conversation_messages WHERE provider=? AND external_message_id=?');$q->execute([$d['provider'],$d['external_message_id']]);if($q->fetchColumn())respond(['duplicate'=>true,'replies'=>[]]);$flowId=$d['flow_id']??db()->query("SELECT id FROM automation_flows WHERE status='published' ORDER BY updated_at DESC LIMIT 1")->fetchColumn();$admin=db()->query("SELECT id,name,email,role FROM users WHERE role='admin' LIMIT 1")->fetch();$result=$flows->message($flowId,$d['conversation_id'],$d['message'],true,$admin);$q=db()->prepare("SELECT id FROM conversations WHERE provider='simulator' AND external_id=?");$q->execute([$d['conversation_id']]);$cid=$q->fetchColumn();db()->prepare("INSERT INTO conversation_messages(id,conversation_id,provider,external_message_id,direction,body,status) VALUES(?,?,?,?, 'in',?,'received')")->execute([uid(),$cid,$d['provider'],$d['external_message_id'],$d['message']]);respond(['duplicate'=>false,'replies'=>$result['replies'],'status'=>$result['status']]);}
 if($path==='/api/users'){$u=auth(['admin','manager','sdr']);respond(['data'=>db()->query("SELECT id,name,role FROM users WHERE active=1 ORDER BY name")->fetchAll()]);}
 if($path==='/api/brokers'){$u=auth(['admin','manager','sdr']);respond(['data'=>db()->query("SELECT id,name,email FROM users WHERE role='broker' AND active=1 ORDER BY name")->fetchAll()]);}
 if($path==='/api/team'&&$method==='GET'){$u=auth(['admin','manager']);respond(['data'=>db()->query("SELECT u.id,u.name,u.email,u.role,u.active,u.creci,u.created_at,(SELECT COUNT(*) FROM opportunities WHERE broker_id=u.id) broker_opportunities,(SELECT COUNT(*) FROM opportunities WHERE sdr_id=u.id) sdr_opportunities,(SELECT COUNT(*) FROM opportunities WHERE broker_id=u.id AND stage='won') broker_won FROM users u ORDER BY FIELD(u.role,'admin','manager','sdr','broker'),u.name")->fetchAll()]);}
 if($path==='/api/team'&&$method==='POST'){$u=auth(['admin']);$id=create_user(json_input());respond(['data'=>['id'=>$id]],201);}
 if(preg_match('#^/api/team/([a-f0-9]{32})$#',$path,$m)&&$method==='PUT'){$u=auth(['admin']);$d=json_input();validate_required($d,['name','email','role']);if(!in_array($d['role'],['admin','manager','sdr','broker','analyst'],true))throw new InvalidArgumentException('Papel inválido.');$active=array_key_exists('active',$d)?(!empty($d['active'])?1:0):1;if($m[1]===$u['id']&&!$active)throw new InvalidArgumentException('Você não pode desativar sua própria conta.');$q=db()->prepare('SELECT 1 FROM users WHERE email=? AND id<>?');$q->execute([$d['email'],$m[1]]);if($q->fetchColumn())throw new InvalidArgumentException('Já existe um usuário com este e-mail.');if(!empty($d['password'])){if(strlen($d['password'])<8)throw new InvalidArgumentException('A senha deve ter ao menos 8 caracteres.');db()->prepare('UPDATE users SET password_hash=? WHERE id=?')->execute([password_hash($d['password'],PASSWORD_DEFAULT),$m[1]]);}db()->prepare('UPDATE users SET name=?,email=?,role=?,active=? WHERE id=?')->execute([$d['name'],$d['email'],$d['role'],$active,$m[1]]);if(array_key_exists('creci',$d))db()->prepare('UPDATE users SET creci=? WHERE id=?')->execute([trim((string)$d['creci'])?:null,$m[1]]);respond(['message'=>'Usuário atualizado.']);}
 if($path==='/api/calendar-events'&&$method==='POST'){$u=auth();$d=json_input();validate_required($d,['title','starts_at']);$responsible=$d['responsible_id']??$u['id'];if(in_array($u['role'],['broker','sdr'],true)&&$responsible!==$u['id'])throw new AuthorizationException('Você só pode criar compromissos para si.');$id=uid();db()->prepare('INSERT INTO calendar_events(id,opportunity_id,responsible_id,title,event_type,starts_at,ends_at,notes,created_by,status) VALUES(?,?,?,?,?,?,?,?,?,?)')->execute([$id,$d['opportunity_id']??null,$responsible,$d['title'],$d['event_type']??'commitment',$d['starts_at'],$d['ends_at']??null,$d['notes']??null,$u['id'],'scheduled']);$ops->audit($u['id'],'calendar_created','calendar_event',$id,'Compromisso criado');respond(['data'=>['id'=>$id]],201);}
 if($path==='/api/calendar-events'&&$method==='GET'){$u=auth();$from=$_GET['from']??date('Y-m-d');$to=$_GET['to']??date('Y-m-d',strtotime('+7 days'));$owner=in_array($u['role'],['broker','sdr'],true)?$u['id']:($_GET['responsible']??null);$q=db()->prepare("SELECT id,opportunity_id,responsible_id,title,'commitment' item_type,starts_at,status FROM calendar_events WHERE starts_at>=? AND starts_at<?".($owner?' AND responsible_id=?':'').' LIMIT 500');$q->execute(array_merge([$from.' 00:00:00',date('Y-m-d H:i:s',strtotime($to.' +1 day'))],$owner?[$owner]:[]));respond(['data'=>$q->fetchAll()]);}
 if($path==='/api/agenda'&&($_GET['type']??'')==='commitment'){$u=auth();$from=$_GET['from']??date('Y-m-d');$to=$_GET['to']??date('Y-m-d',strtotime('+7 days'));$owner=in_array($u['role'],['broker','sdr'],true)?$u['id']:($_GET['responsible']??null);$q=db()->prepare("SELECT id,opportunity_id,responsible_id,title,'commitment' item_type,starts_at,status FROM calendar_events WHERE starts_at>=? AND starts_at<?".($owner?' AND responsible_id=?':'').' LIMIT 500');$q->execute(array_merge([$from.' 00:00:00',date('Y-m-d H:i:s',strtotime($to.' +1 day'))],$owner?[$owner]:[]));respond(['data'=>$q->fetchAll()]);}
 if($path==='/api/agenda'){$u=auth();$from=$_GET['from']??date('Y-m-d');$to=$_GET['to']??date('Y-m-d',strtotime('+7 days'));$type=$_GET['type']??'';$owner=in_array($u['role'],['broker','sdr'],true)?$u['id']:($_GET['responsible']??null);$items=[];if(!$type||$type==='task'){$sql="SELECT id,opportunity_id,assigned_to responsible_id,title,'task' item_type,due_at starts_at,status FROM tasks WHERE due_at>=? AND due_at<?".($owner?' AND assigned_to=?':'').' LIMIT 500';$q=db()->prepare($sql);$q->execute(array_merge([$from.' 00:00:00',date('Y-m-d H:i:s',strtotime($to.' +1 day'))],$owner?[$owner]:[]));$items=array_merge($items,$q->fetchAll());}if(!$type||$type==='visit'){$sql="SELECT id,opportunity_id,broker_id responsible_id,location title,'visit' item_type,scheduled_at starts_at,status FROM visits WHERE scheduled_at>=? AND scheduled_at<?".($owner?' AND broker_id=?':'').' LIMIT 500';$q=db()->prepare($sql);$q->execute(array_merge([$from.' 00:00:00',date('Y-m-d H:i:s',strtotime($to.' +1 day'))],$owner?[$owner]:[]));$items=array_merge($items,$q->fetchAll());}if(!$type||$type==='proposal'){$sql="SELECT id,opportunity_id,created_by responsible_id,CONCAT('Validade de proposta: ',amount) title,'proposal' item_type,CONCAT(valid_until,' 18:00:00') starts_at,status FROM proposals WHERE valid_until BETWEEN ? AND ?".($owner?' AND created_by=?':'').' LIMIT 500';$q=db()->prepare($sql);$q->execute(array_merge([$from,$to],$owner?[$owner]:[]));$items=array_merge($items,$q->fetchAll());}if(!$type||$type==='nurturing'){$sql="SELECT o.id,o.id opportunity_id,o.sdr_id responsible_id,CONCAT('Contato de nutrição: ',c.name) title,'nurturing' item_type,o.next_contact_at starts_at,o.triage_status status FROM opportunities o JOIN contacts c ON c.id=o.contact_id WHERE o.next_contact_at>=? AND o.next_contact_at<?".($owner?' AND o.sdr_id=?':'').' LIMIT 500';$q=db()->prepare($sql);$q->execute(array_merge([$from.' 00:00:00',date('Y-m-d H:i:s',strtotime($to.' +1 day'))],$owner?[$owner]:[]));$items=array_merge($items,$q->fetchAll());}usort($items,fn($a,$b)=>strcmp($a['starts_at'],$b['starts_at']));respond(['data'=>array_slice($items,0,500)]);}
 if(preg_match('#^/api/tasks/([a-f0-9]{32})$#',$path,$m)&&$method==='PUT'){$u=auth();$ops->task($m[1],json_input(),$u);respond(['message'=>'Tarefa atualizada.']);}
 if($path==='/api/notifications'){$u=auth();$q=db()->prepare('SELECT * FROM notifications WHERE user_id=? ORDER BY created_at DESC LIMIT 100');$q->execute([$u['id']]);$rows=$q->fetchAll();respond(['data'=>$rows,'unread'=>count(array_filter($rows,fn($x)=>!$x['read_at']))]);}
 if(preg_match('#^/api/notifications/([a-f0-9]{32})/read$#',$path,$m)&&$method==='PUT'){$u=auth();db()->prepare('UPDATE notifications SET read_at=CURRENT_TIMESTAMP WHERE id=? AND user_id=?')->execute([$m[1],$u['id']]);respond(['message'=>'Notificação lida.']);}
 if($path==='/api/documents'&&$method==='POST'){$u=auth();foreach(['opportunity_id','entity_type','entity_id'] as $f)if(empty($_POST[$f]))throw new InvalidArgumentException('Metadados do documento incompletos.');$ops->canAccess($_POST['opportunity_id'],$u);if(!isset($_FILES['file'])||$_FILES['file']['error']!==UPLOAD_ERR_OK)throw new InvalidArgumentException('Falha no upload.');$max=(int)(getenv('UPLOAD_MAX_BYTES')?:10485760);if($_FILES['file']['size']>$max)throw new InvalidArgumentException('Arquivo acima do limite configurado.');$mime=(new finfo(FILEINFO_MIME_TYPE))->file($_FILES['file']['tmp_name']);$allowed=['application/pdf'=>'pdf','image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp'];if(!isset($allowed[$mime]))throw new InvalidArgumentException('Formato não permitido.');$storage=getenv('PRIVATE_STORAGE_PATH')?:dirname(__DIR__).'/storage/private';if(!is_dir($storage)&&!mkdir($storage,0700,true))throw new RuntimeException('Não foi possível preparar armazenamento privado.');$name=bin2hex(random_bytes(24)).'.'.$allowed[$mime];if(!move_uploaded_file($_FILES['file']['tmp_name'],$storage.'/'.$name))throw new RuntimeException('Falha ao armazenar documento.');$id=uid();db()->prepare('INSERT INTO documents(id,opportunity_id,entity_type,entity_id,uploaded_by,original_name,storage_name,mime_type,size_bytes,sha256) VALUES(?,?,?,?,?,?,?,?,?,?)')->execute([$id,$_POST['opportunity_id'],$_POST['entity_type'],$_POST['entity_id'],$u['id'],basename($_FILES['file']['name']),$name,$mime,$_FILES['file']['size'],hash_file('sha256',$storage.'/'.$name)]);$ops->audit($u['id'],'document_upload','document',$id,'Documento enviado',['mime'=>$mime,'size'=>$_FILES['file']['size']]);respond(['data'=>['id'=>$id,'original_name'=>basename($_FILES['file']['name'])]],201);}
 if(preg_match('#^/api/documents/([a-f0-9]{32})/download$#',$path,$m)&&$method==='GET'){$u=auth();$q=db()->prepare('SELECT * FROM documents WHERE id=? AND deleted_at IS NULL');$q->execute([$m[1]]);$doc=$q->fetch();if(!$doc)throw new RuntimeException('Documento não encontrado.');$ops->canAccess($doc['opportunity_id'],$u);$file=(getenv('PRIVATE_STORAGE_PATH')?:dirname(__DIR__).'/storage/private').'/'.$doc['storage_name'];if(!is_file($file))throw new RuntimeException('Arquivo não encontrado no armazenamento.');$ops->audit($u['id'],'document_download','document',$doc['id'],'Documento consultado');header('Content-Type: '.$doc['mime_type']);header('Content-Length: '.$doc['size_bytes']);header('Content-Disposition: attachment; filename="'.rawurlencode($doc['original_name']).'"');header('X-Content-Type-Options: nosniff');readfile($file);exit;}
 if(preg_match('#^/api/documents/([a-f0-9]{32})$#',$path,$m)&&$method==='DELETE'){$u=auth();$q=db()->prepare('SELECT * FROM documents WHERE id=? AND deleted_at IS NULL');$q->execute([$m[1]]);$doc=$q->fetch();if(!$doc)throw new RuntimeException('Documento não encontrado.');$ops->canAccess($doc['opportunity_id'],$u);db()->prepare('UPDATE documents SET deleted_at=CURRENT_TIMESTAMP,deleted_by=? WHERE id=?')->execute([$u['id'],$m[1]]);$ops->audit($u['id'],'document_delete','document',$m[1],'Documento removido logicamente');respond(['message'=>'Documento removido.']);}
 if(preg_match('#^/api/opportunities/([a-f0-9]{32})/documents$#',$path,$m)){$u=auth();$ops->canAccess($m[1],$u);$q=db()->prepare('SELECT id,entity_type,entity_id,original_name,mime_type,size_bytes,uploaded_by,created_at FROM documents WHERE opportunity_id=? AND deleted_at IS NULL ORDER BY created_at DESC');$q->execute([$m[1]]);respond(['data'=>$q->fetchAll()]);}
 if($path==='/api/reports'||$path==='/api/reports/export'){$u=auth();$parts=[];$args=[];if($u['role']==='broker'){$parts[]='o.broker_id=?';$args[]=$u['id'];}elseif($u['role']==='sdr'){$parts[]='o.sdr_id=?';$args[]=$u['id'];}foreach(['source_id'=>'o.source_id','sdr_id'=>'o.sdr_id','broker_id'=>'o.broker_id','business_type'=>'cl.business_type'] as $key=>$column)if(!empty($_GET[$key])){$parts[]="$column=?";$args[]=$_GET[$key];}if(!empty($_GET['from'])){$parts[]='DATE(o.created_at)>=?';$args[]=$_GET['from'];}if(!empty($_GET['to'])){$parts[]='DATE(o.created_at)<=?';$args[]=$_GET['to'];}$where=$parts?' WHERE '.implode(' AND ',$parts):'';$base=' FROM opportunities o JOIN contacts c ON c.id=o.contact_id JOIN lead_sources s ON s.id=o.source_id LEFT JOIN users su ON su.id=o.sdr_id LEFT JOIN users bu ON bu.id=o.broker_id LEFT JOIN closings cl ON cl.opportunity_id=o.id';if($path==='/api/reports/export'){$q=db()->prepare('SELECT o.created_at,c.name contato,s.name origem,su.name sdr,bu.name corretor,o.stage etapa,o.first_service_at,o.qualified_at,cl.business_type,cl.final_amount,cl.loss_reason'.$base.$where.' ORDER BY o.created_at DESC LIMIT 10000');$q->execute($args);$rows=$q->fetchAll();header('Content-Type: text/csv; charset=UTF-8');header('Content-Disposition: attachment; filename="relatorio-vln.csv"');echo "\xEF\xBB\xBF";$out=fopen('php://output','w');fputcsv($out,['Entrada','Contato','Origem','SDR','Corretor','Etapa','Primeiro contato','Qualificação','Negócio','Valor final','Motivo da perda'],';');foreach($rows as $row)fputcsv($out,array_values($row),';');exit;}$q=db()->prepare("SELECT COUNT(*) leads_received,SUM(o.qualified_at IS NOT NULL) qualified,AVG(CASE WHEN o.first_service_at IS NOT NULL THEN TIMESTAMPDIFF(MINUTE,o.created_at,o.first_service_at) END) avg_first_contact,SUM(o.stage='won') won,SUM(o.stage='lost') lost,SUM(cl.business_type='purchase') sales,SUM(cl.business_type='rental') rentals,SUM(CASE WHEN cl.business_type='purchase' THEN cl.final_amount ELSE 0 END) sales_value,SUM(CASE WHEN cl.business_type='rental' THEN cl.final_amount ELSE 0 END) rentals_value".$base.$where);$q->execute($args);$summary=$q->fetch();$q=db()->prepare('SELECT o.stage,COUNT(*) total'.$base.$where.' GROUP BY o.stage');$q->execute($args);$stages=$q->fetchAll();$q=db()->prepare('SELECT DATE(o.created_at) day,COUNT(*) leads,SUM(o.stage=\'won\') won'.$base.$where.' GROUP BY DATE(o.created_at) ORDER BY day');$q->execute($args);respond(['data'=>['summary'=>$summary,'stages'=>$stages,'daily'=>$q->fetchAll()]]);}
 if($path==='/api/audit'){$u=auth(['admin','manager']);$page=max(1,(int)($_GET['page']??1));$parts=[];$args=[];if(!empty($_GET['user_id'])){$parts[]='a.user_id=?';$args[]=$_GET['user_id'];}if(!empty($_GET['action'])){$parts[]='a.action=?';$args[]=$_GET['action'];}if(!empty($_GET['entity_type'])){$parts[]='a.entity_type=?';$args[]=$_GET['entity_type'];}if(!empty($_GET['q'])){$parts[]='a.summary LIKE ?';$args[]='%'.$_GET['q'].'%';}if(!empty($_GET['from'])){$parts[]='DATE(a.created_at)>=?';$args[]=$_GET['from'];}if(!empty($_GET['to'])){$parts[]='DATE(a.created_at)<=?';$args[]=$_GET['to'];}$where=$parts?' WHERE '.implode(' AND ',$parts):'';$perPage=20;$q=db()->prepare('SELECT COUNT(*) FROM audit_events a'.$where);$q->execute($args);$total=(int)$q->fetchColumn();$q=db()->prepare('SELECT a.*,u.name user_name FROM audit_events a LEFT JOIN users u ON u.id=a.user_id'.$where.' ORDER BY a.created_at DESC LIMIT '.$perPage.' OFFSET '.(($page-1)*$perPage));$q->execute($args);$rows=$q->fetchAll();$actions=db()->query('SELECT DISTINCT action FROM audit_events ORDER BY action')->fetchAll(PDO::FETCH_COLUMN);$entityTypes=db()->query('SELECT DISTINCT entity_type FROM audit_events ORDER BY entity_type')->fetchAll(PDO::FETCH_COLUMN);respond(['data'=>$rows,'page'=>$page,'per_page'=>$perPage,'total'=>$total,'actions'=>$actions,'entity_types'=>$entityTypes]);}
 if($path==='/api/property-types'){auth();respond(['data'=>array_map(fn($t,$g)=>['value'=>$t,'group'=>$g,'condo'=>in_array($t,PropertyService::CONDO_TYPES,true)],array_keys(PropertyService::TYPES),PropertyService::TYPES)]);}
 if($path==='/api/properties/photo-guide'&&$method==='POST'){auth();respond(['data'=>PropertyService::photoGuide(json_input())]);}
 if($path==='/api/properties'&&$method==='GET'){$u=auth();respond($properties->list($u,$_GET));}
 if($path==='/api/properties'&&$method==='POST'){$u=auth(['admin','manager','broker']);respond(['data'=>$properties->create(json_input(),$u)],201);}
 if(preg_match('#^/api/properties/([a-f0-9]{32})$#',$path,$m)&&$method==='GET'){$u=auth();respond(['data'=>$properties->get($m[1],$u)]);}
 if(preg_match('#^/api/properties/([a-f0-9]{32})$#',$path,$m)&&$method==='PUT'){$u=auth(['admin','manager','broker']);respond(['data'=>$properties->update($m[1],json_input(),$u)]);}
 if(preg_match('#^/api/properties/([a-f0-9]{32})/submit$#',$path,$m)&&$method==='POST'){$u=auth(['admin','manager','broker']);respond(['data'=>$properties->submit($m[1],$u)]);}
 if(preg_match('#^/api/properties/([a-f0-9]{32})/review$#',$path,$m)&&$method==='POST'){$u=auth(['admin','manager']);$d=json_input();validate_required($d,['decision']);respond(['data'=>$properties->review($m[1],$d['decision'],$d['notes']??null,$u)]);}
 if(preg_match('#^/api/properties/([a-f0-9]{32})/photos$#',$path,$m)&&$method==='POST'){$u=auth(['admin','manager','broker']);if(empty($_FILES['file']))throw new InvalidArgumentException('Nenhuma foto enviada.');respond(['data'=>$properties->addPhoto($m[1],$_FILES['file'],(string)($_POST['slot']??'other'),$_POST['caption']??null,$u)],201);}
 if(preg_match('#^/api/properties/([a-f0-9]{32})/photos/([a-f0-9]{32})/cover$#',$path,$m)&&$method==='POST'){$u=auth(['admin','manager','broker']);respond(['data'=>$properties->setCover($m[1],$m[2],$u)]);}
 if(preg_match('#^/api/properties/([a-f0-9]{32})/photos/([a-f0-9]{32})$#',$path,$m)&&$method==='DELETE'){$u=auth(['admin','manager','broker']);respond(['data'=>$properties->removePhoto($m[1],$m[2],$u)]);}
 if($path==='/api/commercial/metrics'){$u=auth();$scope=$u['role']==='broker'?' WHERE broker_id=?':'';$args=$u['role']==='broker'?[$u['id']]:[];$q=db()->prepare("SELECT SUM(status='scheduled') visits_scheduled,SUM(status='completed') visits_completed FROM visits".$scope);$q->execute($args);$visits=$q->fetch();$proposalScope=$u['role']==='broker'?' WHERE created_by=?':'';$q=db()->prepare("SELECT COUNT(*) proposals_created,SUM(status='accepted') proposals_accepted,SUM(status='rejected') proposals_rejected FROM proposals".$proposalScope);$q->execute($args);$proposals=$q->fetch();$closingScope=$u['role']==='broker'?' WHERE responsible_id=?':'';$q=db()->prepare("SELECT SUM(outcome='won' AND business_type='purchase') sales_closed,SUM(outcome='won' AND business_type='rental') rentals_closed,SUM(CASE WHEN outcome='won' AND business_type='purchase' THEN final_amount ELSE 0 END) sales_value,SUM(CASE WHEN outcome='won' AND business_type='rental' THEN final_amount ELSE 0 END) rentals_value FROM closings".$closingScope);$q->execute($args);$closing=$q->fetch();$q=db()->prepare("SELECT SUM(stage='negotiation') negotiations FROM opportunities".$scope);$q->execute($args);$neg=$q->fetch();$loss=db()->query("SELECT loss_reason,COUNT(*) total FROM closings WHERE outcome='lost' GROUP BY loss_reason ORDER BY total DESC")->fetchAll();$conversion=db()->query("SELECT u.name broker_name,COUNT(o.id) opportunities,SUM(o.stage='won') won,ROUND(100*SUM(o.stage='won')/NULLIF(COUNT(o.id),0),1) conversion_rate FROM users u LEFT JOIN opportunities o ON o.broker_id=u.id WHERE u.role='broker' GROUP BY u.id,u.name")->fetchAll();respond(['data'=>array_merge($visits?:[],$proposals?:[],$closing?:[],$neg?:[],['losses'=>$loss,'conversion_by_broker'=>$conversion])]);}
 if($path==='/api/visit-statuses'&&$method==='GET'){$u=auth();respond(['data'=>db()->query('SELECT * FROM visit_statuses ORDER BY sort_order')->fetchAll()]);}
 if($path==='/api/visit-statuses'&&$method==='POST'){$u=auth(['admin','manager']);$d=json_input();validate_required($d,['label']);$key=preg_replace('/[^a-z0-9_]+/','_',strtolower(trim($d['label'])));$key=trim($key,'_')?:('status_'.substr(uid(),0,8));$q=db()->prepare('SELECT 1 FROM visit_statuses WHERE `key`=?');$q->execute([$key]);if($q->fetchColumn())$key=$key.'_'.substr(uid(),0,6);$q=db()->prepare('SELECT COALESCE(MAX(sort_order),-1)+1 FROM visit_statuses');$q->execute();$order=(int)$q->fetchColumn();$id=uid();db()->prepare('INSERT INTO visit_statuses(id,`key`,label,color,sort_order) VALUES(?,?,?,?,?)')->execute([$id,$key,$d['label'],$d['color']??'#2563eb',$order]);respond(['data'=>['id'=>$id,'key'=>$key]],201);}
 if(preg_match('#^/api/visit-statuses/([a-f0-9]{32})$#',$path,$m)&&$method==='DELETE'){$u=auth(['admin','manager']);$q=db()->prepare('SELECT * FROM visit_statuses WHERE id=?');$q->execute([$m[1]]);$row=$q->fetch();if(!$row)throw new RuntimeException('Status não encontrado.');$q=db()->prepare('SELECT COUNT(*) FROM visits WHERE status=?');$q->execute([$row['key']]);if($q->fetchColumn())throw new InvalidArgumentException('Existem visitas com este status; mova-as antes de excluir a coluna.');db()->prepare('DELETE FROM visit_statuses WHERE id=?')->execute([$m[1]]);respond(['message'=>'Status removido.']);}
 if($path==='/api/visits'){$u=auth(['admin','manager','broker']);$where=$u['role']==='broker'?' WHERE v.broker_id=?':'';$q=db()->prepare('SELECT v.*,c.name contact_name,p.title property_title,u.name broker_name FROM visits v JOIN opportunities o ON o.id=v.opportunity_id JOIN contacts c ON c.id=o.contact_id JOIN properties p ON p.id=v.property_id JOIN users u ON u.id=v.broker_id'.$where.' ORDER BY v.scheduled_at');$q->execute($u['role']==='broker'?[$u['id']]:[]);respond(['data'=>$q->fetchAll()]);}
 if($path==='/api/commercial/overview'){$u=auth(['admin','manager']);$parts=[];$args=[];if(!empty($_GET['q'])){$parts[]='(c.name LIKE ? OR c.email LIKE ? OR c.phone LIKE ?)';$args=array_merge($args,array_fill(0,3,'%'.$_GET['q'].'%'));}if(!empty($_GET['broker_id'])){$parts[]='o.broker_id=?';$args[]=$_GET['broker_id'];}if(!empty($_GET['stage'])){$parts[]='o.stage=?';$args[]=$_GET['stage'];}if(!empty($_GET['from'])){$parts[]='DATE(o.updated_at)>=?';$args[]=$_GET['from'];}if(!empty($_GET['to'])){$parts[]='DATE(o.updated_at)<=?';$args[]=$_GET['to'];}$where=$parts?' WHERE '.implode(' AND ',$parts):'';$page=max(1,(int)($_GET['page']??1));$perPage=24;$base='FROM opportunities o JOIN contacts c ON c.id=o.contact_id LEFT JOIN users u ON u.id=o.broker_id'.$where;$q=db()->prepare('SELECT COUNT(*) '.$base);$q->execute($args);$total=(int)$q->fetchColumn();$q=db()->prepare('SELECT o.*,c.name,u.name broker_name '.$base.' ORDER BY o.updated_at DESC LIMIT '.$perPage.' OFFSET '.(($page-1)*$perPage));$q->execute($args);respond(['data'=>$q->fetchAll(),'page'=>$page,'per_page'=>$perPage,'total'=>$total]);}
 if(preg_match('#^/api/commercial/([a-f0-9]{32})$#',$path,$m)&&$method==='GET'){$u=auth();authorize_opportunity($u,$m[1]);$lead=$svc->get($m[1]);foreach(['visits'=>'SELECT v.*,p.title property_title FROM visits v JOIN properties p ON p.id=v.property_id WHERE opportunity_id=? ORDER BY scheduled_at DESC','proposals'=>'SELECT pr.*,p.title property_title FROM proposals pr JOIN properties p ON p.id=pr.property_id WHERE opportunity_id=? ORDER BY pr.created_at DESC','properties'=>'SELECT p.*,op.presented_at,op.notes presentation_notes FROM opportunity_properties op JOIN properties p ON p.id=op.property_id WHERE op.opportunity_id=?','negotiations'=>'SELECT n.*,u.name user_name FROM negotiations n JOIN users u ON u.id=n.user_id WHERE opportunity_id=? ORDER BY n.created_at DESC'] as $key=>$sql){$q=db()->prepare($sql);$q->execute([$m[1]]);$lead[$key]=$q->fetchAll();}$q=db()->prepare('SELECT * FROM closings WHERE opportunity_id=?');$q->execute([$m[1]]);$lead['closing']=$q->fetch()?:null;respond(['data'=>$lead]);}
 if(preg_match('#^/api/commercial/([a-f0-9]{32})/interaction$#',$path,$m)&&$method==='POST'){$u=auth(['admin','manager','broker']);authorize_opportunity($u,$m[1]);$commercial->interaction($m[1],json_input(),$u);respond(['message'=>'Interação registrada.'],201);}
 if(preg_match('#^/api/commercial/([a-f0-9]{32})/properties$#',$path,$m)&&$method==='POST'){$u=auth(['admin','manager','broker']);authorize_opportunity($u,$m[1]);$d=json_input();validate_required($d,['property_id']);$commercial->present($m[1],$d['property_id'],$u,$d['notes']??null);respond(['message'=>'Imóvel apresentado.'],201);}
 if(preg_match('#^/api/commercial/([a-f0-9]{32})/visits$#',$path,$m)&&$method==='POST'){$u=auth(['admin','manager','broker']);authorize_opportunity($u,$m[1]);$v=$commercial->visit($m[1],json_input(),$u);$ops->notify($v['broker_id'],'visit:'.$v['id'].':created','Nova visita','Uma visita foi agendada.','visit',$v['id']);$ops->audit($u['id'],'visit_created','visit',$v['id'],'Visita criada');respond(['data'=>$v],201);}
 if(preg_match('#^/api/visits/([a-f0-9]{32})$#',$path,$m)&&$method==='PUT'){$u=auth(['admin','manager','broker']);$v=$commercial->visitUpdate($m[1],json_input(),$u);$ops->notify($v['broker_id'],'visit:'.$v['id'].':'.$v['status'].':'.$v['updated_at'],'Visita atualizada','Status: '.$v['status'],'visit',$v['id']);$ops->audit($u['id'],'visit_'.$v['status'],'visit',$v['id'],'Visita atualizada');respond(['data'=>$v]);}
 if(preg_match('#^/api/commercial/([a-f0-9]{32})/proposals$#',$path,$m)&&$method==='POST'){$u=auth(['admin','manager','broker']);authorize_opportunity($u,$m[1]);respond(['data'=>$commercial->proposal($m[1],json_input(),$u)],201);}
 if(preg_match('#^/api/proposals/([a-f0-9]{32})$#',$path,$m)&&$method==='PUT'){$u=auth(['admin','manager','broker']);$p=$commercial->proposalUpdate($m[1],json_input(),$u);$ops->audit($u['id'],'proposal_updated','proposal',$p['id'],'Proposta atualizada',['status'=>$p['status'],'amount'=>$p['amount']]);respond(['data'=>$p]);}
 if(preg_match('#^/api/commercial/([a-f0-9]{32})/negotiations$#',$path,$m)&&$method==='POST'){$u=auth(['admin','manager','broker']);authorize_opportunity($u,$m[1]);$commercial->negotiate($m[1],json_input(),$u);respond(['message'=>'Negociação registrada.'],201);}
 if(preg_match('#^/api/commercial/([a-f0-9]{32})/close$#',$path,$m)&&$method==='POST'){$u=auth(['admin','manager','broker']);authorize_opportunity($u,$m[1]);$d=json_input();$commercial->close($m[1],$d,$u);$o=$ops->canAccess($m[1],$u);if($o['broker_id'])$ops->notify($o['broker_id'],'opportunity:'.$m[1].':closed:'.$o['closed_at'],'Oportunidade encerrada','Resultado: '.$d['outcome'],'opportunity',$m[1]);$ops->audit($u['id'],'opportunity_closed','opportunity',$m[1],'Oportunidade encerrada',['outcome'=>$d['outcome']]);respond(['message'=>'Oportunidade encerrada.'],201);}
 if(preg_match('#^/api/commercial/([a-f0-9]{32})/reopen$#',$path,$m)&&$method==='POST'){$u=auth(['admin','manager']);$d=json_input();$commercial->reopen($m[1],$d['reason']??'',$u);$o=$ops->canAccess($m[1],$u);if($o['broker_id'])$ops->notify($o['broker_id'],'opportunity:'.$m[1].':reopened:'.$o['reopened_at'],'Oportunidade reaberta','A oportunidade retornou à negociação.','opportunity',$m[1]);$ops->audit($u['id'],'opportunity_reopened','opportunity',$m[1],'Oportunidade reaberta');respond(['message'=>'Oportunidade reaberta.']);}
 if($path==='/api/sdr/inbox'){$u=auth(['admin','manager','sdr']);$parts=["o.triage_status IN ('pending','contacted')"];$args=[];if($u['role']==='sdr'){$parts[]='o.sdr_id=?';$args[]=$u['id'];}foreach(['source_id'=>'o.source_id','status'=>'o.triage_status','responsible'=>'o.sdr_id'] as $key=>$col)if(!empty($_GET[$key])){$parts[]="$col=?";$args[]=$_GET[$key];}if(!empty($_GET['from'])){$parts[]='DATE(o.created_at)>=?';$args[]=$_GET['from'];}if(!empty($_GET['to'])){$parts[]='DATE(o.created_at)<=?';$args[]=$_GET['to'];}if(($_GET['deadline']??'')==='overdue')$parts[]='o.first_service_at IS NULL AND o.first_contact_due_at<CURRENT_TIMESTAMP';if(($_GET['deadline']??'')==='near')$parts[]='o.first_service_at IS NULL AND o.first_contact_due_at BETWEEN CURRENT_TIMESTAMP AND DATE_ADD(CURRENT_TIMESTAMP,INTERVAL 15 MINUTE)';$page=max(1,(int)($_GET['page']??1));$perPage=20;$base='FROM opportunities o JOIN contacts c ON c.id=o.contact_id JOIN lead_sources s ON s.id=o.source_id LEFT JOIN users u ON u.id=o.sdr_id WHERE '.implode(' AND ',$parts);$q=db()->prepare('SELECT COUNT(*) '.$base);$q->execute($args);$total=(int)$q->fetchColumn();$q=db()->prepare('SELECT o.*,c.name,c.email,c.phone,s.name source_name,u.name sdr_name '.$base.' ORDER BY o.first_contact_due_at,o.created_at LIMIT '.$perPage.' OFFSET '.(($page-1)*$perPage));$q->execute($args);respond(['data'=>$q->fetchAll(),'page'=>$page,'per_page'=>$perPage,'total'=>$total]);}
 if($path==='/api/sdr/nurturing'){$u=auth(['admin','manager','sdr']);$where="o.triage_status='nurturing'";$args=[];if($u['role']==='sdr'){$where.=' AND o.sdr_id=?';$args[]=$u['id'];}$page=max(1,(int)($_GET['page']??1));$perPage=20;$base="FROM opportunities o JOIN contacts c ON c.id=o.contact_id LEFT JOIN users u ON u.id=o.sdr_id WHERE $where";$q=db()->prepare('SELECT COUNT(*) '.$base);$q->execute($args);$total=(int)$q->fetchColumn();$q=db()->prepare("SELECT o.*,c.name,c.email,c.phone,u.name sdr_name,(CASE WHEN o.next_contact_at<CURRENT_TIMESTAMP THEN 'overdue' WHEN DATE(o.next_contact_at)=CURRENT_DATE THEN 'today' ELSE 'future' END) contact_timing ".$base.' ORDER BY o.next_contact_at LIMIT '.$perPage.' OFFSET '.(($page-1)*$perPage));$q->execute($args);respond(['data'=>$q->fetchAll(),'page'=>$page,'per_page'=>$perPage,'total'=>$total]);}
 if($path==='/api/distribution/queue'){$u=auth(['admin','manager','sdr']);$q=db()->prepare("SELECT o.*,c.name,c.email,c.phone,s.name source_name FROM opportunities o JOIN contacts c ON c.id=o.contact_id JOIN lead_sources s ON s.id=o.source_id WHERE o.triage_status='qualified' AND o.broker_id IS NULL".($u['role']==='sdr'?' AND o.sdr_id=?':'').' ORDER BY o.qualified_at');$q->execute($u['role']==='sdr'?[$u['id']]:[]);respond(['data'=>$q->fetchAll()]);}
 if($path==='/api/my-opportunities'){$u=auth(['broker']);$q=db()->prepare('SELECT o.*,c.name,c.email,c.phone,s.name source_name FROM opportunities o JOIN contacts c ON c.id=o.contact_id JOIN lead_sources s ON s.id=o.source_id WHERE o.broker_id=? ORDER BY o.distributed_at DESC');$q->execute([$u['id']]);respond(['data'=>$q->fetchAll()]);}
 if($path==='/api/distribution/settings'){$u=auth(['admin','manager']);if($method==='GET')respond(['data'=>db()->query('SELECT * FROM distribution_settings WHERE id=1')->fetch()]);$d=json_input();db()->prepare('UPDATE distribution_settings SET automatic_enabled=?,updated_by=? WHERE id=1')->execute([!empty($d['automatic_enabled'])?1:0,$u['id']]);respond(['data'=>db()->query('SELECT * FROM distribution_settings WHERE id=1')->fetch()]);}
 if(preg_match('#^/api/leads/([a-f0-9]{32})/contact$#',$path,$m)&&$method==='POST'){$u=auth(['admin','manager','sdr']);authorize_opportunity($u,$m[1]);respond(['data'=>$sdr->contact($m[1],json_input(),$u)]);}
 if(preg_match('#^/api/leads/([a-f0-9]{32})/qualify$#',$path,$m)&&$method==='POST'){$u=auth(['admin','manager','sdr']);authorize_opportunity($u,$m[1]);respond(['data'=>$sdr->qualify($m[1],json_input(),$u)]);}
 if(preg_match('#^/api/leads/([a-f0-9]{32})/distribute$#',$path,$m)&&$method==='POST'){$u=auth(['admin','manager','sdr']);authorize_opportunity($u,$m[1]);$d=json_input();$before=$svc->get($m[1]);$result=$sdr->distribute($m[1],$d['broker_id']??null,$u,$d['reason']??null,!empty($d['automatic']));$kind=$before['broker_id']?'redistributed':'assigned';$ops->notify($result['broker_id'],"opportunity:$m[1]:$kind:".$result['distributed_at'],$kind==='assigned'?'Nova oportunidade':'Oportunidade redistribuída','Uma oportunidade foi atribuída à sua carteira.','opportunity',$m[1]);$ops->audit($u['id'],$kind,'opportunity',$m[1],$kind==='assigned'?'Oportunidade distribuída':'Oportunidade redistribuída',['previous'=>$before['broker_id'],'new'=>$result['broker_id']]);respond(['data'=>$result]);}
 if(preg_match('#^/api/leads/([a-f0-9]{32})/broker-status$#',$path,$m)&&$method==='POST'){$u=auth(['admin','manager','broker']);authorize_opportunity($u,$m[1]);$d=json_input();respond(['data'=>$sdr->brokerStatus($m[1],$d['status']??'',$u)]);}
 if($path==='/api/dashboard'){$u=auth();$where='';$args=[];if($u['role']==='broker'){$where=' WHERE broker_id=?';$args=[$u['id']];}elseif($u['role']==='sdr'){$where=' WHERE sdr_id=?';$args=[$u['id']];}$q=db()->prepare("SELECT COUNT(*) total,SUM(stage='qualification') qualification,SUM(stage='service') service,SUM(stage='visit') visit,SUM(stage='proposal') proposal,SUM(stage='negotiation') negotiation,SUM(stage='won') won,SUM(stage='lost') lost,SUM(first_service_at IS NULL AND triage_status IN ('pending','contacted')) awaiting_first_contact,SUM(triage_status='nurturing') nurturing,SUM(broker_id IS NULL AND triage_status='qualified') undistributed,AVG(CASE WHEN first_service_at IS NOT NULL THEN TIMESTAMPDIFF(MINUTE,created_at,first_service_at) END) avg_first_contact_minutes FROM opportunities".$where);$q->execute($args);$stats=$q->fetch();$taskWhere=$u['role']==='broker'?' AND assigned_to=?':'';$q=db()->prepare("SELECT SUM(status='pending' AND due_at<=DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 7 DAY)) pending_tasks,SUM(status='pending' AND due_at<CURRENT_TIMESTAMP) overdue_followups FROM tasks WHERE 1=1".$taskWhere);$q->execute($u['role']==='broker'?$args:[]);$extra=$q->fetch();$q=db()->query("SELECT u.name broker_name,COUNT(*) total FROM distributions d JOIN users u ON u.id=d.new_broker_id GROUP BY u.id,u.name ORDER BY total DESC");$byBroker=$q->fetchAll();$q=db()->query("SELECT u.name sdr_name,COUNT(*) total FROM opportunities o JOIN users u ON u.id=o.sdr_id WHERE o.qualified_at IS NOT NULL AND o.qualified_at>=DATE_SUB(CURRENT_TIMESTAMP,INTERVAL 30 DAY) GROUP BY u.id,u.name ORDER BY total DESC");respond(['data'=>array_merge($stats?:[],$extra?:[],['by_broker'=>$byBroker,'qualified_by_sdr'=>$q->fetchAll()])]);}
 if($path==='/api/leads'&&$method==='GET'){$u=auth();$term=trim($_GET['q']??'');$stage=$_GET['stage']??'';$parts=[];$args=[];if($term!==''){$parts[]='(c.name LIKE ? OR c.email LIKE ? OR c.phone LIKE ?)';$args=array_merge($args,array_fill(0,3,'%'.$term.'%'));}if($stage!==''){$parts[]='o.stage=?';$args[]=$stage;}if($u['role']==='broker'){$parts[]='o.broker_id=?';$args[]=$u['id'];}elseif($u['role']==='sdr'){$parts[]='o.sdr_id=?';$args[]=$u['id'];}$where=$parts?' WHERE '.implode(' AND ',$parts):'';$page=max(1,(int)($_GET['page']??1));$perPage=20;$base='FROM opportunities o JOIN contacts c ON c.id=o.contact_id JOIN lead_sources s ON s.id=o.source_id LEFT JOIN users u ON u.id=o.broker_id'.$where;$q=db()->prepare('SELECT COUNT(*) '.$base);$q->execute($args);$total=(int)$q->fetchColumn();$sql='SELECT o.id,o.stage,o.interest_type,o.region,o.min_value,o.max_value,o.created_at,c.name,c.email,c.phone,s.name source_name,u.name broker_name '.$base.' ORDER BY o.created_at DESC LIMIT '.$perPage.' OFFSET '.(($page-1)*$perPage);$q=db()->prepare($sql);$q->execute($args);respond(['data'=>$q->fetchAll(),'page'=>$page,'per_page'=>$perPage,'total'=>$total]);}
 if($path==='/api/leads'&&$method==='POST'){$u=auth(['admin','manager','sdr']);respond(['data'=>$svc->create(json_input(),$u['id'])],201);}
 if(preg_match('#^/api/leads/([a-f0-9]{32})$#',$path,$m)){$u=auth();authorize_opportunity($u,$m[1]);if($method==='GET')respond(['data'=>$svc->get($m[1])]);if($method==='PUT'){$d=json_input();$old=$svc->get($m[1]);$allowed=['name','email','phone','region','min_value','max_value','property_interest'];$sets=[];$args=[];foreach($allowed as $f)if(array_key_exists($f,$d)){if(in_array($f,['name','email','phone']))continue;$sets[]="$f=?";$args[]=$d[$f]?:null;}if($sets){$args[]=$m[1];db()->prepare('UPDATE opportunities SET '.implode(',',$sets).' WHERE id=?')->execute($args);}if(isset($d['name'])||isset($d['email'])||isset($d['phone'])){db()->prepare('UPDATE contacts SET name=?,email=?,phone=? WHERE id=?')->execute([$d['name']??$old['name'],$d['email']??$old['email'],$d['phone']??$old['phone'],$old['contact_id']]);}db()->prepare('INSERT INTO interactions(id,opportunity_id,user_id,type,description) VALUES(?,?,?,?,?)')->execute([uid(),$m[1],$u['id'],'updated','Cadastro atualizado']);respond(['data'=>$svc->get($m[1])]);}}
 if(preg_match('#^/api/leads/([a-f0-9]{32})/stage$#',$path,$m)&&$method==='PUT'){$u=auth();authorize_opportunity($u,$m[1]);$d=json_input();respond(['data'=>$svc->move($m[1],$d['stage']??'',$d['loss_reason']??null,$u['id'])]);}
 if(preg_match('#^/api/leads/([a-f0-9]{32})/tasks$#',$path,$m)&&$method==='POST'){$u=auth();authorize_opportunity($u,$m[1]);$d=json_input();validate_required($d,['title','due_at']);$assigned=$d['assigned_to']??$u['id'];if($u['role']==='broker'&&$assigned!==$u['id'])respond(['message'=>'Corretor só pode atribuir tarefas a si.'],403);db()->prepare('INSERT INTO tasks(id,opportunity_id,assigned_to,title,due_at) VALUES(?,?,?,?,?)')->execute([uid(),$m[1],$assigned,$d['title'],$d['due_at']]);db()->prepare('INSERT INTO interactions(id,opportunity_id,user_id,type,description) VALUES(?,?,?,?,?)')->execute([uid(),$m[1],$u['id'],'task_created','Follow-up: '.$d['title']]);respond(['message'=>'Tarefa criada.'],201);}
 if($path==='/api/import/csv'&&$method==='POST'){$u=auth(['admin','manager','sdr']);if(!isset($_FILES['file'])||$_FILES['file']['error'])throw new InvalidArgumentException('Envie o arquivo CSV.');$h=fopen($_FILES['file']['tmp_name'],'r');$headers=fgetcsv($h,0,',');$required=['name','source_code','interest_type'];if(array_diff($required,$headers?:[]))throw new InvalidArgumentException('Cabeçalhos obrigatórios: '.implode(', ',$required));$ok=[];$errors=[];$line=1;while(($row=fgetcsv($h,0,','))!==false){$line++;try{if(count($row)!==count($headers))throw new InvalidArgumentException('Número de colunas diferente do cabeçalho.');$d=array_combine($headers,$row);$q=db()->prepare('SELECT id FROM lead_sources WHERE code=?');$q->execute([$d['source_code']]);$d['source_id']=$q->fetchColumn();if(!$d['source_id'])throw new InvalidArgumentException('Fonte desconhecida.');$ok[]=$svc->create($d,$u['id'])['id'];}catch(InvalidArgumentException|DomainException $e){$errors[]=['line'=>$line,'message'=>$e->getMessage()];}catch(Throwable $e){if(get_class($e)===RuntimeException::class){$errors[]=['line'=>$line,'message'=>$e->getMessage()];}else{$ref=log_internal_error($e);$errors[]=['line'=>$line,'message'=>'Erro interno ao importar esta linha (código '.$ref.').','error_id'=>$ref];}}}respond(['accepted'=>count($ok),'rejected'=>count($errors),'ids'=>$ok,'errors'=>$errors]);}
 if($path==='/api/webhooks/local'&&$method==='POST'){$provided=$_SERVER['HTTP_X_WEBHOOK_TOKEN']??'';$expected=getenv('WEBHOOK_TOKEN')?:'';if(!$expected||!hash_equals($expected,$provided))respond(['message'=>'Token de webhook inválido.'],401);$d=json_input();$q=db()->prepare("SELECT id FROM lead_sources WHERE code='local'");$q->execute();$source=$q->fetchColumn();$event=uid();$safe=$d;foreach(['password','token','secret','authorization'] as $k)if(isset($safe[$k]))$safe[$k]='[REDACTED]';db()->prepare('INSERT INTO integration_events(id,source_id,external_id,payload,payload_hash,status) VALUES(?,?,?,?,?,?)')->execute([$event,$source,$d['external_id']??null,json_encode($safe),hash('sha256',json_encode($d)),'received']);try{$d['source_id']=$source;$lead=$svc->create($d);db()->prepare("UPDATE integration_events SET status='processed',result_message='Lead criado',processed_at=CURRENT_TIMESTAMP WHERE id=?")->execute([$event]);respond(['event_id'=>$event,'lead_id'=>$lead['id']],201);}catch(Throwable $e){$status=$e instanceof DomainException?'duplicate':'rejected';db()->prepare('UPDATE integration_events SET status=?,result_message=?,processed_at=CURRENT_TIMESTAMP WHERE id=?')->execute([$status,mb_substr($e->getMessage(),0,255),$event]);throw $e;}}
 respond(['message'=>'Rota não encontrada.'],404);
} catch(RateLimitException $e){respond(['message'=>$e->getMessage()],429);} catch(IntegrationException $e){error_log($e->getMessage());respond(['message'=>$e->getMessage()],502);} catch(AuthorizationException $e){respond(['message'=>$e->getMessage()],403);} catch(InvalidArgumentException|DomainException $e){respond(['message'=>$e->getMessage()],422);} catch(RuntimeException $e){if(get_class($e)===RuntimeException::class)respond(['message'=>$e->getMessage()],404);internal_error($e);} catch(Throwable $e){internal_error($e);}
