import {useEffect,useRef,useState} from 'react';
import {Link} from 'react-router-dom';
import {api} from '../lib/api';
import {Icon} from './Icon';

type FlowNode={id:string;type:string;config:Record<string,string>;next?:string|null;yes?:string|null;no?:string|null};
type Flow={id:string;name:string;status:string;graph:string|{nodes?:FlowNode[]};version_number:number;validation_errors?:string|null};

const definitions=[
  {type:'start',label:'Início',help:'Ponto inicial do atendimento',icon:'▶',tone:'start'},
  {type:'message',label:'Mensagem',help:'Envia uma mensagem automática',icon:'✦',tone:'message'},
  {type:'question',label:'Pergunta',help:'Pergunta e guarda a resposta',icon:'?',tone:'question'},
  {type:'condition',label:'Condição',help:'Cria caminhos por uma resposta',icon:'◇',tone:'condition'},
  {type:'create_lead',label:'Criar oportunidade',help:'Registra o lead no CRM',icon:'+',tone:'lead'},
  {type:'human',label:'Atendimento humano',help:'Transfere para a equipe',icon:'◎',tone:'human'},
  {type:'end',label:'Encerrar',help:'Finaliza a automação',icon:'■',tone:'end'},
];
const definition=(type:string)=>definitions.find(x=>x.type===type)||definitions[1];
const newNode=(type:string):FlowNode=>({id:`${type}_${Date.now().toString(36)}`,type,config:type==='message'?{text:'Olá! Como posso ajudar?'}:type==='question'?{text:'Como podemos chamar você?','field':'name'}:type==='condition'?{field:'resposta',contains:'sim'}:type==='create_lead'?{interest_type:'purchase'}:{},next:null});

function parseGraph(flow:Flow):FlowNode[]{try{const graph=typeof flow.graph==='string'?JSON.parse(flow.graph):flow.graph;return Array.isArray(graph?.nodes)?graph.nodes:[]}catch{return []}}

export function ModernFlowBuilder(){
  const [flows,setFlows]=useState<Flow[]>([]),[selected,setSelected]=useState<Flow|null>(null),[nodes,setNodes]=useState<FlowNode[]>([]),[name,setName]=useState('Novo fluxo'),[feedback,setFeedback]=useState(''),[saving,setSaving]=useState(false),[sidebarOpen,setSidebarOpen]=useState(true);
  const load=()=>api('/flows').then(r=>setFlows(r.data));
  useEffect(()=>{void load()},[]);
  function choose(flow:Flow){setSelected(flow);setName(flow.name);setNodes(parseGraph(flow));setFeedback('')}
  function createNew(){setSelected(null);setName('Novo fluxo');setNodes([newNode('start')]);setFeedback('')}
  function add(type:string){if(type==='start'&&nodes.some(n=>n.type==='start')){setFeedback('O fluxo já possui um bloco de início.');return}const node=newNode(type);setNodes(current=>{const copy=current.map(x=>({...x}));const previous=[...copy].reverse().find(x=>!['end','human','condition'].includes(x.type)&&!x.next);if(previous)previous.next=node.id;return [...copy,node]});setFeedback('')}
  function patchNode(id:string,change:Partial<FlowNode>){setNodes(current=>current.map(node=>node.id===id?{...node,...change}:node))}
  function patchConfig(id:string,key:string,value:string){setNodes(current=>current.map(node=>node.id===id?{...node,config:{...node.config,[key]:value}}:node))}
  function remove(id:string){setNodes(current=>current.filter(x=>x.id!==id).map(x=>({...x,next:x.next===id?null:x.next,yes:x.yes===id?null:x.yes,no:x.no===id?null:x.no})))}
  async function save(){setSaving(true);try{const result=await api('/flows',{method:'POST',body:JSON.stringify({id:selected?.id,name,graph:{nodes}})});setFeedback(result.data.errors.length?'Revise o fluxo: '+result.data.errors.join(' · '):'Rascunho salvo e validado com sucesso.');await load();if(!selected)setSelected({id:result.data.id,name,status:'draft',graph:{nodes},version_number:1})}catch(e:any){setFeedback(e.message)}finally{setSaving(false)}}
  async function publish(){if(!selected)return;setSaving(true);try{await api(`/flows/${selected.id}/publish`,{method:'POST'});setFeedback('Fluxo publicado com sucesso.');await load()}catch(e:any){setFeedback(e.message)}finally{setSaving(false)}}
  return <div className="automation-page">
    <header className="studio-header"><div><span className="eyebrow">Automação</span><h1>Builder de Fluxos</h1><p>Crie jornadas de atendimento, conecte as etapas e valide antes de publicar.</p></div><div className="studio-actions"><Link className="button secondary" to="/simulador">Testar conversa</Link><button className="secondary" onClick={createNew}>Novo fluxo</button><button onClick={save} disabled={saving||!name.trim()}>{saving?'Salvando…':'Salvar rascunho'}</button><button className="publish-button" disabled={saving||!selected} onClick={publish}>Publicar</button></div></header>
    {feedback&&<div className={`studio-feedback ${feedback.includes('sucesso')||feedback.includes('validado')?'success':''}`}><span>{feedback.includes('sucesso')||feedback.includes('validado')?'✓':'!'}</span>{feedback}</div>}
    <div className={`flow-studio ${sidebarOpen?'':'palette-collapsed'}`}>
      <aside className="flow-palette"><div className="palette-heading"><div><strong>Blocos</strong><small>Arraste ou clique para adicionar</small></div><button onClick={()=>setSidebarOpen(false)} aria-label="Recolher blocos">‹</button></div><div className="block-catalog">{definitions.map(item=><button key={item.type} draggable onDragStart={e=>e.dataTransfer.setData('type',item.type)} onClick={()=>add(item.type)}><span className={item.tone}>{item.icon}</span><div><strong>{item.label}</strong><small>{item.help}</small></div><b>＋</b></button>)}</div><div className="saved-flows"><div><strong>Seus fluxos</strong><button onClick={createNew}>＋</button></div>{flows.map(flow=><button key={flow.id} className={selected?.id===flow.id?'active':''} onClick={()=>choose(flow)}><span>{flow.name.slice(0,2).toUpperCase()}</span><div><strong>{flow.name}</strong><small>v{flow.version_number} · {flow.status==='published'?'Publicado':'Rascunho'}</small></div></button>)}{!flows.length&&<p>Nenhum fluxo salvo.</p>}</div></aside>
      {!sidebarOpen&&<button className="open-palette" onClick={()=>setSidebarOpen(true)} aria-label="Abrir blocos">›</button>}
      <main className="flow-workspace" onDragOver={e=>e.preventDefault()} onDrop={e=>add(e.dataTransfer.getData('type'))}>
        <div className="workspace-toolbar"><label>Nome do fluxo<input value={name} onChange={e=>setName(e.target.value)} placeholder="Ex.: Captação pelo site"/></label><div><span className="status-dot"/> {selected?.status==='published'?'Publicado':'Rascunho'} <b>•</b> {nodes.length} blocos</div></div>
        <div className="flow-canvas"><div className="canvas-dots"/>{nodes.length?<div className="node-stack">{nodes.map((node,index)=>{const meta=definition(node.type);return <div className="node-wrap" key={node.id}>{index>0&&<span className="node-connector"><i>↓</i></span>}<article className={`visual-node ${meta.tone}`}><div className="node-head"><span>{meta.icon}</span><div><strong>{meta.label}</strong><small>{node.id}</small></div><button onClick={()=>remove(node.id)} disabled={node.type==='start'} aria-label={`Remover ${meta.label}`}>×</button></div><div className="node-body">
          {node.type==='start'&&<p>A conversa entra no fluxo por este bloco.</p>}
          {['message','question'].includes(node.type)&&<label>Texto da mensagem<textarea value={node.config.text||''} onChange={e=>patchConfig(node.id,'text',e.target.value)} rows={3}/></label>}
          {node.type==='question'&&<label>Salvar resposta no campo<input value={node.config.field||''} onChange={e=>patchConfig(node.id,'field',e.target.value)} placeholder="Ex.: name"/></label>}
          {node.type==='condition'&&<div className="node-fields"><label>Campo<input value={node.config.field||''} onChange={e=>patchConfig(node.id,'field',e.target.value)}/></label><label>Contém<input value={node.config.contains||''} onChange={e=>patchConfig(node.id,'contains',e.target.value)}/></label></div>}
          {node.type==='create_lead'&&<label>Tipo de interesse<select value={node.config.interest_type||'purchase'} onChange={e=>patchConfig(node.id,'interest_type',e.target.value)}><option value="purchase">Compra</option><option value="rental">Locação</option></select></label>}
          {node.type==='human'&&<p>A automação será pausada para atendimento da equipe.</p>}{node.type==='end'&&<p>A conversa será concluída.</p>}
          {!['end','human','condition'].includes(node.type)&&<label>Próxima etapa<select value={node.next||''} onChange={e=>patchNode(node.id,{next:e.target.value||null})}><option value="">Selecione uma saída</option>{nodes.filter(x=>x.id!==node.id).map(x=><option key={x.id} value={x.id}>{definition(x.type).label} · {x.id.split('_').at(-1)}</option>)}</select></label>}
          {node.type==='condition'&&<div className="node-fields"><label>Se verdadeiro<select value={node.config.yes||''} onChange={e=>patchConfig(node.id,'yes',e.target.value)}><option value="">Escolha</option>{nodes.filter(x=>x.id!==node.id).map(x=><option key={x.id} value={x.id}>{definition(x.type).label}</option>)}</select></label><label>Se falso<select value={node.config.no||''} onChange={e=>patchConfig(node.id,'no',e.target.value)}><option value="">Escolha</option>{nodes.filter(x=>x.id!==node.id).map(x=><option key={x.id} value={x.id}>{definition(x.type).label}</option>)}</select></label></div>}
        </div></article></div>})}<button className="add-step" onClick={()=>add('message')}>＋ Adicionar próxima etapa</button></div>:<div className="canvas-empty"><span>✦</span><h2>Comece sua automação</h2><p>Adicione um bloco de início e monte a jornada de atendimento.</p><button onClick={()=>add('start')}>Adicionar início</button></div>}</div>
      </main>
    </div>
  </div>
}

type ChatMessage={id:string;side:'customer'|'bot'|'error';text:string;time:string};
export function ConversationSimulator(){
  const [flows,setFlows]=useState<Flow[]>([]),[flow,setFlow]=useState(''),[conversation,setConversation]=useState(()=>crypto.randomUUID()),[input,setInput]=useState(''),[messages,setMessages]=useState<ChatMessage[]>([]),[trace,setTrace]=useState<any>(),[integrated,setIntegrated]=useState(false),[sending,setSending]=useState(false);
  const bottom=useRef<HTMLDivElement>(null);
  useEffect(()=>{api('/flows').then(r=>{setFlows(r.data);if(r.data[0])setFlow(r.data[0].id)})},[]);useEffect(()=>bottom.current?.scrollIntoView({behavior:'smooth'}),[messages]);
  const stamp=()=>new Intl.DateTimeFormat('pt-BR',{hour:'2-digit',minute:'2-digit'}).format(new Date());
  async function send(e:React.FormEvent){e.preventDefault();const text=input.trim();if(!text||!flow||sending)return;setInput('');setMessages(list=>[...list,{id:crypto.randomUUID(),side:'customer',text,time:stamp()}]);setSending(true);try{const result=await api('/simulator/message',{method:'POST',body:JSON.stringify({flow_id:flow,conversation_id:conversation,message:text,integrated})});setMessages(list=>[...list,...result.data.replies.map((reply:string)=>({id:crypto.randomUUID(),side:'bot' as const,text:reply,time:stamp()}))]);setTrace(result.data)}catch(e:any){setMessages(list=>[...list,{id:crypto.randomUUID(),side:'error',text:e.message,time:stamp()}])}finally{setSending(false)}}
  async function reset(){await api('/simulator/reset',{method:'POST',body:JSON.stringify({conversation_id:conversation})}).catch(()=>{});setConversation(crypto.randomUUID());setMessages([]);setTrace(undefined)}
  const selected=flows.find(x=>x.id===flow);
  return <div className="conversation-page"><header className="studio-header"><div><span className="eyebrow">Ambiente seguro de testes</span><h1>Simulador de Conversas</h1><p>Teste a experiência do cliente sem enviar mensagens para canais reais.</p></div><div className="studio-actions"><Link className="button secondary" to="/fluxos">Voltar ao builder</Link><button className="secondary" onClick={reset}>Reiniciar conversa</button></div></header>
    <div className="conversation-layout"><section className="messenger"><div className="messenger-top"><span className="contact-avatar"><Icon name="building"/></span><div><strong>Atendimento IMOB HUB</strong><small><i/> Simulação local ativa</small></div><button aria-label="Mais opções">•••</button></div><div className="chat-wallpaper"><div className="encryption-note">🔒 Ambiente local de simulação. Nenhuma mensagem será enviada externamente.</div>{!messages.length&&<div className="chat-welcome"><span>💬</span><h2>Inicie a conversa</h2><p>Envie uma mensagem como se você fosse o cliente.</p></div>}{messages.map(message=><div key={message.id} className={`message-row ${message.side}`}><div className="message-bubble"><p>{message.text}</p><small>{message.time}{message.side==='customer'&&' ✓✓'}</small></div></div>)}{sending&&<div className="message-row bot"><div className="typing"><i/><i/><i/></div></div>}<div ref={bottom}/></div><form className="message-composer" onSubmit={send}><button type="button" aria-label="Adicionar">＋</button><input value={input} onChange={e=>setInput(e.target.value)} placeholder="Digite uma mensagem" aria-label="Mensagem"/><button className="send-message" disabled={!input.trim()||!flow||sending} aria-label="Enviar">➤</button></form></section>
      <aside className="simulation-panel"><div className="panel-section"><span className="eyebrow">Configuração</span><h2>Executar cenário</h2><label>Fluxo em teste<select value={flow} onChange={e=>{setFlow(e.target.value);void reset()}}><option value="">Selecione um fluxo</option>{flows.map(item=><option key={item.id} value={item.id}>{item.name} · v{item.version_number}</option>)}</select></label><label className="integration-switch"><span><strong>Teste integrado local</strong><small>Permite criar um lead marcado como teste.</small></span><input type="checkbox" checked={integrated} onChange={e=>setIntegrated(e.target.checked)}/><i/></label></div><div className="panel-section flow-summary"><h3>Fluxo selecionado</h3>{selected?<><div className="flow-identity"><span>{selected.name.slice(0,2).toUpperCase()}</span><div><strong>{selected.name}</strong><small>Versão {selected.version_number} · {selected.status}</small></div></div><dl><dt>Status da execução</dt><dd><span className={`run-status ${trace?.status||'idle'}`}>{trace?.status||'Aguardando'}</span></dd><dt>Blocos percorridos</dt><dd>{trace?.path?.length||0}</dd><dt>Lead de teste</dt><dd>{trace?.lead_id?'Criado':'Não criado'}</dd></dl></>:<p className="panel-empty">Escolha um fluxo para iniciar.</p>}</div><details className="technical-trace"><summary>Detalhes técnicos da execução</summary><pre>{trace?JSON.stringify(trace,null,2):'Nenhuma execução registrada.'}</pre></details></aside>
    </div>
  </div>
}
