import {useCallback,useEffect,useMemo,useState} from 'react';
import {Link} from 'react-router-dom';
import {api,date,money,stages} from '../lib/api';
import type {AppUser} from './AppLayout';
import {Icon} from './Icon';

type DashboardData={dashboard:any;commercial:any;leads:any[];agenda:any[];properties:any[]};

const today=()=>new Date().toISOString().slice(0,10);
function Section({title,link,to,children,className=''}:{title:string;link?:string;to?:string;children:React.ReactNode;className?:string}){return <section className={`dash-card ${className}`}><div className="section-heading"><h2>{title}</h2>{link&&to&&<Link to={to}>{link} <span>→</span></Link>}</div>{children}</section>}
function Skeleton(){return <div className="dashboard-skeleton" aria-label="Carregando painel"><div/><div/><div/><div/><section/><section/><section/></div>}
function StatCard({label,value,detail,icon,tone}:{label:string;value:any;detail:string;icon:string;tone:string}){return <article className={`stat-card ${tone}`}><span className="stat-icon"><Icon name={icon}/></span><div><small>{label}</small><strong>{value??0}</strong><p>{detail}</p></div><svg className="spark" viewBox="0 0 80 28" aria-hidden="true"><path d="M2 24 C15 23 17 13 30 16 S45 26 55 12 S68 8 78 3"/></svg></article>}

export function Dashboard({user}:{user:AppUser}){
  const [data,setData]=useState<DashboardData|null>(null),[error,setError]=useState('');
  const load=useCallback(async()=>{setError('');try{const day=today();const requests=[api('/dashboard'),api('/commercial/metrics'),api('/leads'),api(`/agenda?from=${day}&to=${day}`),api('/properties?listing_status=approved&per_page=3')];const results=await Promise.allSettled(requests);if(results[0].status==='rejected')throw results[0].reason;const value=(i:number,fallback:any)=>results[i].status==='fulfilled'?(results[i] as PromiseFulfilledResult<any>).value.data:fallback;setData({dashboard:value(0,{}),commercial:value(1,{}),leads:value(2,[]),agenda:value(3,[]),properties:value(4,[])})}catch(e:any){setError(e.message||'Não foi possível carregar o painel.')}},[]);
  useEffect(()=>{void load()},[load]);
  const sources=useMemo(()=>{const map=new Map<string,number>();for(const lead of data?.leads||[])map.set(lead.source_name||'Sem origem',(map.get(lead.source_name||'Sem origem')||0)+1);return [...map].sort((a,b)=>b[1]-a[1])},[data]);
  const maxFunnel=Math.max(1,...Object.keys(stages).map(k=>Number(data?.dashboard?.[k]||0)),Number(data?.dashboard?.total||0));
  const tasks=(data?.agenda||[]).filter(x=>x.item_type==='task'&&x.status==='pending');
  async function completeTask(id:string){await api('/tasks/'+id,{method:'PUT',body:JSON.stringify({action:'complete'})});load()}
  if(error)return <div className="state-card"><h2>Não foi possível carregar o dashboard</h2><p>{error}</p><button onClick={load}>Tentar novamente</button></div>;
  if(!data)return <Skeleton/>;
  const firstName=user.name.trim().split(/\s+/)[0];
  const funnel=[['qualification','Qualificação'],['service','Atendimento'],['visit','Visitas'],['proposal','Propostas'],['negotiation','Negociações'],['won','Vendas']];
  return <div className="dashboard-page">
    <header className="dashboard-header"><div><h1>Olá, {firstName}!</h1><p>Aqui está o panorama do seu negócio hoje.</p></div><div className="date-chip"><Icon name="calendar"/><span>{new Intl.DateTimeFormat('pt-BR',{dateStyle:'long'}).format(new Date())}</span></div></header>
    <div className="stat-grid"><StatCard label="Leads" value={data.dashboard.total||0} detail="oportunidades no CRM" icon="leads" tone="blue"/><StatCard label="Visitas" value={data.commercial.visits_scheduled||0} detail={`${data.commercial.visits_completed||0} realizadas`} icon="home" tone="orange"/><StatCard label="Propostas" value={data.commercial.proposals_created||0} detail={`${data.commercial.proposals_accepted||0} aceitas`} icon="file" tone="blue"/><StatCard label="Vendas" value={data.commercial.sales_closed||0} detail={money(data.commercial.sales_value)} icon="briefcase" tone="green"/></div>
    <div className="dashboard-grid top-grid">
      <Section title="Funil de Vendas" className="funnel-card"><div className="funnel-list">{funnel.map(([key,label],index)=>{const total=Number(data.dashboard[key]||0),pct=Math.round(total/maxFunnel*100);return <div className="funnel-row" key={key}><span className="funnel-shape" style={{width:`${Math.max(28,100-index*11)}%`}}/><span>{label}</span><strong>{total}</strong><small>{pct}%</small></div>})}</div></Section>
      <Section title="Leads por Origem" className="source-card">{sources.length?<div className="source-content"><div className="donut" style={{background:`conic-gradient(${sources.map(([,n],i)=>`var(--chart-${i%6}) ${sources.slice(0,i).reduce((s,x)=>s+x[1],0)/(data.leads.length||1)*100}% ${(sources.slice(0,i).reduce((s,x)=>s+x[1],0)+n)/(data.leads.length||1)*100}%`).join(',')})`}}><span><strong>{data.leads.length}</strong><small>Leads</small></span></div><div className="source-legend">{sources.slice(0,6).map(([name,total],i)=><div key={name}><i style={{background:`var(--chart-${i})`}}/><span>{name}</span><strong>{Math.round(total/data.leads.length*100)}%</strong></div>)}</div></div>:<p className="empty-inline">Nenhuma origem com leads cadastrados.</p>}</Section>
      <Section title="Atividades de Hoje" link="Ver agenda" to="/agenda-operacional" className="activities-card"><div className="activity-list">{data.agenda.slice(0,6).map(item=><div key={`${item.item_type}-${item.id}`}><time>{new Date(item.starts_at.replace(' ','T')).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}</time><i/><span className={`activity-icon ${item.item_type}`}><Icon name={item.item_type==='visit'?'home':item.item_type==='task'?'check':'file'}/></span><p><strong>{item.title}</strong><small>{item.item_type==='task'?'Tarefa':item.item_type==='visit'?'Visita':'Compromisso'} · {item.status}</small></p></div>)}{!data.agenda.length&&<p className="empty-inline">Nenhuma atividade prevista para hoje.</p>}</div></Section>
    </div>
    <div className="dashboard-grid bottom-grid">
      <Section title="Últimos Leads" link="Ver todos" to="/leads" className="recent-card"><div className="compact-table"><table><thead><tr><th>Nome</th><th>Origem</th><th>Interesse</th><th>Status</th><th>Data</th></tr></thead><tbody>{data.leads.slice(0,5).map(lead=><tr key={lead.id}><td><span className="lead-avatar">{lead.name.slice(0,2).toUpperCase()}</span><strong>{lead.name}</strong></td><td>{lead.source_name}</td><td>{lead.property_interest||lead.region||lead.interest_type}</td><td><span className={`badge ${lead.stage}`}>{stages[lead.stage]||lead.stage}</span></td><td>{date(lead.created_at)}</td></tr>)}</tbody></table>{!data.leads.length&&<p className="empty-inline">Nenhum lead cadastrado.</p>}</div></Section>
      <Section title="Imóveis em Destaque" link="Ver todos" to="/imoveis" className="properties-card"><div className="property-list">{data.properties.slice(0,3).map((item,i)=><div key={item.id}><span className={`property-thumb thumb-${i}`}><Icon name="building"/></span><p><strong>{item.title}</strong><small>{item.region||item.property_type||'Localização não informada'}</small><b>{money(item.price)}</b></p></div>)}{!data.properties.length&&<p className="empty-inline">Nenhum imóvel cadastrado.</p>}</div></Section>
      <Section title="Tarefas Pendentes" link="Ver todas" to="/agenda-operacional" className="tasks-card"><div className="pending-list">{tasks.slice(0,5).map(item=><label key={item.id}><input type="checkbox" onChange={()=>completeTask(item.id)} aria-label={`Concluir ${item.title}`}/><span>{item.title}</span><time>{new Date(item.starts_at.replace(' ','T')).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}</time></label>)}{!tasks.length&&<p className="empty-inline">Nenhuma tarefa pendente para hoje.</p>}</div></Section>
    </div>
    <Section title="Desempenho no Tempo" className="performance-card"><div className="chart-legend"><span><i/>Leads</span><span><i/>Visitas</span><span><i/>Vendas</span></div><div className="performance-chart" aria-label="Distribuição dos leads recentes"><div className="chart-grid"/>{Array.from({length:12},(_,i)=>{const value=data.leads.filter((_,index)=>index%12===i).length;return <span key={i} style={{height:`${Math.max(8,Math.min(88,value*12))}%`}} title={`${value} leads`}/>})}<svg viewBox="0 0 100 40" preserveAspectRatio="none" aria-hidden="true"><polyline points="0,34 9,30 18,31 27,22 36,25 45,17 54,20 63,12 72,17 81,9 90,14 100,7"/></svg></div><p className="chart-note">Visualização baseada nos registros disponíveis na consulta atual.</p></Section>
  </div>
}
