<?php
declare(strict_types=1);
require __DIR__.'/../src/bootstrap.php';require __DIR__.'/../src/LeadService.php';require __DIR__.'/../src/SdrService.php';require __DIR__.'/../src/CommercialService.php';require __DIR__.'/../src/OperationsService.php';
$pdo=db();if($pdo->getAttribute(PDO::ATTR_DRIVER_NAME)!=='mysql')throw new RuntimeException('Este teste exige MySQL.');
$source=$pdo->query("SELECT id FROM lead_sources WHERE code='local'")->fetchColumn();$sdr=$pdo->query("SELECT id FROM users WHERE role='sdr' LIMIT 1")->fetchColumn();$broker=$pdo->query("SELECT id FROM users WHERE role='broker' LIMIT 1")->fetchColumn();$admin=$pdo->query("SELECT id FROM users WHERE role='admin' LIMIT 1")->fetchColumn();
$leads=new LeadService($pdo);$sdrFlow=new SdrService($pdo);$commercial=new CommercialService($pdo);$suffix=bin2hex(random_bytes(4));
$lead=$leads->create(['name'=>'Teste MySQL','email'=>"mysql-$suffix@test.local",'source_id'=>$source,'external_id'=>"mysql-$suffix",'interest_type'=>'purchase'],$admin);$sdrUser=['id'=>$sdr,'role'=>'sdr'];$brokerUser=['id'=>$broker,'role'=>'broker'];$adminUser=['id'=>$admin,'role'=>'admin'];
$sdrFlow->contact($lead['id'],['result'=>'completed'],$sdrUser);$sdrFlow->qualify($lead['id'],['result'=>'qualified','property_type'=>'Casa'],$sdrUser);$sdrFlow->distribute($lead['id'],$broker,$sdrUser);$sdrFlow->brokerStatus($lead['id'],'received',$brokerUser);
$property=uid();$pdo->prepare('INSERT INTO properties(id,reference_code,title,property_type,region,purpose,price,listing_status) VALUES(?,?,?,?,?,?,?,?)')->execute([$property,"MYSQL-$suffix",'Casa teste','Casa','Centro','purchase',750000,'approved']);$commercial->present($lead['id'],$property,$brokerUser,'Teste integrado');$visit=$commercial->visit($lead['id'],['property_id'=>$property,'scheduled_at'=>'2031-05-10 09:00:00','location'=>'Centro'],$brokerUser);try{$commercial->visit($lead['id'],['property_id'=>$property,'scheduled_at'=>'2031-05-10 09:30:00','location'=>'Centro'],$brokerUser);assert(false);}catch(DomainException $e){}$commercial->visitUpdate($visit['id'],['status'=>'completed','feedback'=>'Positivo'],$brokerUser);
$proposal=$commercial->proposal($lead['id'],['property_id'=>$property,'proposal_type'=>'purchase','amount'=>730000,'proposal_date'=>'2031-05-10'],$brokerUser);$commercial->proposalUpdate($proposal['id'],['status'=>'sent'],$brokerUser);$commercial->proposalUpdate($proposal['id'],['status'=>'under_review'],$brokerUser);$commercial->negotiate($lead['id'],['proposal_id'=>$proposal['id'],'amount'=>740000,'notes'=>'Contraproposta aceita'],$brokerUser);$commercial->close($lead['id'],['outcome'=>'won','closing_date'=>'2031-05-12','property_id'=>$property,'business_type'=>'purchase','final_amount'=>740000,'contract_reference'=>"CTR-$suffix"],$brokerUser);$commercial->reopen($lead['id'],'Validação de reabertura',$adminUser);
$q=$pdo->prepare('SELECT COUNT(*) FROM proposal_events WHERE proposal_id=?');$q->execute([$proposal['id']]);assert((int)$q->fetchColumn()===3);assert($leads->get($lead['id'])['stage']==='negotiation');$ops=new OperationsService($pdo);$ops->notify($broker,"mysql:$suffix",'Teste MySQL','Notificação única');$ops->notify($broker,"mysql:$suffix",'Teste MySQL','Notificação única');$q=$pdo->prepare('SELECT COUNT(*) FROM notifications WHERE event_key=?');$q->execute(["mysql:$suffix"]);assert((int)$q->fetchColumn()===1);$ops->audit($admin,'mysql_test','opportunity',$lead['id'],'Auditoria MySQL',['token'=>'não-gravar','ok'=>true]);$q=$pdo->prepare("SELECT metadata FROM audit_events WHERE entity_id=? AND action='mysql_test'");$q->execute([$lead['id']]);assert(!str_contains($q->fetchColumn(),'não-gravar'));
echo "OK MySQL: fluxos comerciais, notificações únicas e auditoria segura.\n";
