<?php
declare(strict_types=1);
final class ConversationService {
 public function __construct(private PDO $db){}
 public function list(array $u): array {$scope='';$args=[];if($u['role']==='broker'){$scope=" WHERE c.assigned_to=? OR (c.assigned_to IS NULL AND c.status='human')";$args[]=$u['id'];}$q=$this->db->prepare("SELECT c.id,c.provider,c.phone,c.status,c.assigned_to,c.updated_at,ct.name contact_name,o.id opportunity_id,au.name assigned_name,p.title property_title,p.reference_code property_reference,(SELECT body FROM conversation_messages m WHERE m.conversation_id=c.id ORDER BY m.created_at DESC LIMIT 1) last_message,(SELECT direction FROM conversation_messages m WHERE m.conversation_id=c.id ORDER BY m.created_at DESC LIMIT 1) last_direction FROM conversations c LEFT JOIN contacts ct ON ct.id=c.contact_id LEFT JOIN opportunities o ON o.id=c.opportunity_id LEFT JOIN users au ON au.id=c.assigned_to LEFT JOIN properties p ON p.id=c.property_id".$scope." ORDER BY c.updated_at DESC LIMIT 200");$q->execute($args);return $q->fetchAll();}
 public function get(string $id, array $u): array {$c=$this->find($id);$this->guard($c,$u,false);$q=$this->db->prepare('SELECT c.*,ct.name contact_name,ct.email contact_email,ct.phone contact_phone,au.name assigned_name,p.title property_title,p.reference_code property_reference FROM conversations c LEFT JOIN contacts ct ON ct.id=c.contact_id LEFT JOIN users au ON au.id=c.assigned_to LEFT JOIN properties p ON p.id=c.property_id WHERE c.id=?');$q->execute([$id]);$c=$q->fetch();unset($c['visitor_token_hash']);$q=$this->db->prepare('SELECT m.*,su.name sender_name FROM conversation_messages m LEFT JOIN users su ON su.id=m.sender_user_id WHERE conversation_id=? ORDER BY m.created_at ASC');$q->execute([$id]);$c['messages']=$q->fetchAll();return $c;}
 public function assign(string $id, array $u): array {$c=$this->find($id);if($u['role']==='broker'&&$c['assigned_to']&&$c['assigned_to']!==$u['id'])throw new AuthorizationException('Conversa já assumida por outro atendente.');$this->db->prepare('UPDATE conversations SET assigned_to=? WHERE id=?')->execute([$u['id'],$id]);return $this->get($id,$u);}
 public function reply(string $id, string $body, array $u): array {$c=$this->find($id);$this->guard($c,$u,true);if(!$c['assigned_to'])$this->db->prepare('UPDATE conversations SET assigned_to=? WHERE id=?')->execute([$u['id'],$id]);if($c['status']==='closed')throw new DomainException('Conversa encerrada não recebe novas mensagens.');if(trim($body)==='')throw new InvalidArgumentException('Mensagem vazia.');$this->db->prepare("INSERT INTO conversation_messages(id,conversation_id,provider,external_message_id,direction,body,status,sender_user_id,created_at) VALUES(?,?,?,?,'out',?,'sent',?,?)")->execute([uid(),$id,$c['provider'],'human-'.uid(),$body,$u['id'],now_micro()]);$this->db->prepare('UPDATE conversations SET updated_at=CURRENT_TIMESTAMP WHERE id=?')->execute([$id]);return $this->get($id,$u);}
 public function resolve(string $id, array $u): array {$this->guard($this->find($id),$u,true);$this->db->prepare("UPDATE conversations SET status='closed' WHERE id=?")->execute([$id]);return $this->get($id,$u);}
 /** Corretor só enxerga conversas livres na fila humana ou assumidas por ele; para responder/encerrar precisa ser o responsável ou assumir. */
 private function guard(array $c, array $u, bool $write): void {if($u['role']!=='broker')return;if($c['assigned_to']===$u['id'])return;if(!$c['assigned_to']&&$c['status']==='human')return;throw new AuthorizationException('Esta conversa está com outro atendente.');}
 private function find(string $id): array {$q=$this->db->prepare('SELECT * FROM conversations WHERE id=?');$q->execute([$id]);$c=$q->fetch();if(!$c)throw new RuntimeException('Conversa não encontrada.');return $c;}
}
