<?php
declare(strict_types=1);
final class OperationsService {
 public function __construct(private PDO $db){}
 public function canAccess(string $oid,array $u):array{$q=$this->db->prepare('SELECT * FROM opportunities WHERE id=?');$q->execute([$oid]);$o=$q->fetch();if(!$o)throw new RuntimeException('Oportunidade não encontrada.');if($u['role']==='broker'&&$o['broker_id']!==$u['id'])throw new AuthorizationException('Oportunidade pertence a outro corretor.');if($u['role']==='sdr'&&$o['sdr_id']!==$u['id'])throw new AuthorizationException('Lead pertence a outro SDR.');return $o;}
 public function notify(string $uid,string $key,string $title,string $message,?string $type=null,?string $id=null):void{$sql=$this->db->getAttribute(PDO::ATTR_DRIVER_NAME)==='mysql'?'INSERT IGNORE INTO notifications(id,user_id,event_key,title,message,entity_type,entity_id) VALUES(?,?,?,?,?,?,?)':'INSERT OR IGNORE INTO notifications(id,user_id,event_key,title,message,entity_type,entity_id) VALUES(?,?,?,?,?,?,?)';$this->db->prepare($sql)->execute([uid(),$uid,$key,$title,$message,$type,$id]);}
 public function audit(?string $uid,string $action,string $type,string $id,string $summary,array $meta=[]):void{$safe=$meta;foreach(['password','token','secret','authorization','content'] as $k)unset($safe[$k]);$this->db->prepare('INSERT INTO audit_events(id,user_id,action,entity_type,entity_id,summary,metadata) VALUES(?,?,?,?,?,?,?)')->execute([uid(),$uid,$action,$type,$id,$summary,$safe?json_encode($safe):null]);}
 public function task(string $id,array $d,array $u):void{$q=$this->db->prepare('SELECT * FROM tasks WHERE id=?');$q->execute([$id]);$t=$q->fetch();if(!$t)throw new RuntimeException('Tarefa não encontrada.');if(in_array($u['role'],['broker','sdr'],true)&&$t['assigned_to']!==$u['id'])throw new AuthorizationException('Tarefa pertence a outro usuário.');$action=$d['action']??'';if($action==='complete')$this->db->prepare("UPDATE tasks SET status='done',completed_at=CURRENT_TIMESTAMP,completed_by=? WHERE id=?")->execute([$u['id'],$id]);elseif($action==='reschedule'){validate_required($d,['due_at']);$this->db->prepare("UPDATE tasks SET status='pending',due_at=? WHERE id=?")->execute([$d['due_at'],$id]);}elseif($action==='cancel'){validate_required($d,['reason']);$this->db->prepare("UPDATE tasks SET status='cancelled',cancelled_at=CURRENT_TIMESTAMP,cancelled_by=?,cancellation_reason=? WHERE id=?")->execute([$u['id'],$d['reason'],$id]);}else throw new InvalidArgumentException('Ação de tarefa inválida.');$this->audit($u['id'],'task_'.$action,'task',$id,'Tarefa atualizada');}
}
