<?php
declare(strict_types=1);
final class SdrService {
 public function __construct(private PDO $db){}
 private function event(string $id,string $user,string $type,string $text,array $meta=[]):void{$q=$this->db->prepare('INSERT INTO interactions(id,opportunity_id,user_id,type,description,metadata) VALUES(?,?,?,?,?,?)');$q->execute([uid(),$id,$user,$type,$text,$meta?json_encode($meta):null]);}
 public function contact(string $id,array $d,array $user):array{
  validate_required($d,['result']); if(!in_array($d['result'],['attempt','completed'],true))throw new InvalidArgumentException('Resultado de contato inválido.');
  $o=$this->opportunity($id); if($user['role']==='sdr'&&$o['sdr_id']!==$user['id'])throw new AuthorizationException('Lead não atribuído a este SDR.');
  $first=$d['result']==='completed'?'COALESCE(first_service_at,CURRENT_TIMESTAMP)':'first_service_at';
  $q=$this->db->prepare("UPDATE opportunities SET first_service_at=$first,triage_status=?,next_contact_at=? WHERE id=?");$q->execute([$d['result']==='completed'?'contacted':$o['triage_status'],!empty($d['next_contact_at'])?$d['next_contact_at']:$o['next_contact_at'],$id]);
  $this->event($id,$user['id'],'contact_'.$d['result'],($d['result']==='completed'?'Contato concluído':'Tentativa de contato').(!empty($d['notes'])?': '.$d['notes']:''));return $this->opportunity($id);
 }
 public function qualify(string $id,array $d,array $user):array{
  validate_required($d,['result']);$valid=['qualified','nurturing','no_interest','invalid','duplicate'];if(!in_array($d['result'],$valid,true))throw new InvalidArgumentException('Resultado da triagem inválido.');
  $o=$this->opportunity($id);if($user['role']==='sdr'&&$o['sdr_id']!==$user['id'])throw new AuthorizationException('Lead não atribuído a este SDR.');
  if(in_array($d['result'],['no_interest','invalid'],true)&&empty(trim((string)($d['reason']??''))))throw new InvalidArgumentException('O motivo é obrigatório para este resultado.');
  if($d['result']==='nurturing'){validate_required($d,['reason','next_contact_at']);}
  $stage=$d['result']==='nurturing'?'nurturing':(in_array($d['result'],['no_interest','invalid','duplicate'],true)?'lost':'qualification');
  $q=$this->db->prepare('UPDATE opportunities SET interest_type=COALESCE(?,interest_type),property_type=?,region=COALESCE(?,region),min_value=COALESCE(?,min_value),max_value=COALESCE(?,max_value),decision_timing=?,needs=?,qualification_notes=?,triage_status=?,stage=?,nurture_reason=?,next_contact_at=?,loss_reason=?,qualified_at=? WHERE id=?');
  $q->execute([$d['interest_type']??null,$d['property_type']??null,$d['region']??null,$d['min_value']??null,$d['max_value']??null,$d['decision_timing']??null,$d['needs']??null,$d['notes']??null,$d['result'],$stage,$d['result']==='nurturing'?$d['reason']:null,!empty($d['next_contact_at'])?$d['next_contact_at']:null,in_array($d['result'],['no_interest','invalid','duplicate'],true)?($d['reason']??'Duplicado'):null,$d['result']==='qualified'?date('Y-m-d H:i:s'):null,$id]);
  if($d['result']==='nurturing'){$q=$this->db->prepare('INSERT INTO tasks(id,opportunity_id,assigned_to,title,due_at) VALUES(?,?,?,?,?)');$q->execute([uid(),$id,$o['sdr_id']?:$user['id'],'Follow-up de nutrição',$d['next_contact_at']]);}
  $this->event($id,$user['id'],'qualification','Triagem: '.$d['result'],['reason'=>$d['reason']??null]);return $this->opportunity($id);
 }
 public function distribute(string $id,?string $brokerId,array $user,?string $reason=null,bool $automatic=false):array{
  $this->db->beginTransaction();try{$o=$this->opportunity($id,true);$previous=$o['broker_id'];if($previous&&$previous!==$brokerId&&$user['role']==='sdr')throw new AuthorizationException('Redistribuição é permitida somente para gestor ou administrador.');if($previous&&$previous!==$brokerId&&!trim((string)$reason))throw new InvalidArgumentException('Informe o motivo da redistribuição.');
   $method=$previous?'redistribution':($automatic?'round_robin':'manual');if($automatic){$lock=$this->db->getAttribute(PDO::ATTR_DRIVER_NAME)==='mysql'?' FOR UPDATE':'';$q=$this->db->query('SELECT * FROM distribution_settings WHERE id=1'.$lock);$settings=$q->fetch();if(!$settings||!$settings['automatic_enabled'])throw new DomainException('Rodízio automático está desativado.');$brokers=$this->db->query("SELECT id FROM users WHERE role='broker' AND active=1 ORDER BY id".$lock)->fetchAll(PDO::FETCH_COLUMN);if(!$brokers)throw new DomainException('Nenhum corretor ativo disponível.');$pos=array_search($settings['last_broker_id'],$brokers,true);$brokerId=$brokers[$pos===false?0:(($pos+1)%count($brokers))];$this->db->prepare('UPDATE distribution_settings SET last_broker_id=?,updated_by=? WHERE id=1')->execute([$brokerId,$user['id']]);}
   if(!$brokerId)throw new InvalidArgumentException('Selecione um corretor.');$q=$this->db->prepare("SELECT id,name FROM users WHERE id=? AND role='broker' AND active=1");$q->execute([$brokerId]);$broker=$q->fetch();if(!$broker)throw new InvalidArgumentException('Corretor inexistente ou inativo.');
   $this->db->prepare("UPDATE opportunities SET broker_id=?,distributed_at=CURRENT_TIMESTAMP,received_at=NULL,service_started_at=NULL,stage='service' WHERE id=?")->execute([$brokerId,$id]);$this->db->prepare('INSERT INTO distributions(id,opportunity_id,previous_broker_id,new_broker_id,distributed_by,method,reason) VALUES(?,?,?,?,?,?,?)')->execute([uid(),$id,$previous,$brokerId,$user['id'],$method,$reason]);$this->event($id,$user['id'],'distribution',($previous?'Redistribuído':'Distribuído').' para '.$broker['name'],['previous'=>$previous,'new'=>$brokerId,'method'=>$method,'reason'=>$reason]);$this->db->commit();return $this->opportunity($id);
  }catch(Throwable $e){if($this->db->inTransaction())$this->db->rollBack();throw $e;}
 }
 public function brokerStatus(string $id,string $status,array $user):array{if(!in_array($status,['received','started'],true))throw new InvalidArgumentException('Status inválido.');$o=$this->opportunity($id);if($user['role']==='broker'&&$o['broker_id']!==$user['id'])throw new AuthorizationException('Oportunidade pertence a outro corretor.');$field=$status==='received'?'received_at':'service_started_at';$this->db->prepare("UPDATE opportunities SET $field=CURRENT_TIMESTAMP WHERE id=?")->execute([$id]);$this->event($id,$user['id'],'broker_'.$status,$status==='received'?'Recebimento confirmado':'Atendimento comercial iniciado');return $this->opportunity($id);}
 private function opportunity(string $id,bool $lock=false):array{$sql='SELECT * FROM opportunities WHERE id=?'.($lock&&$this->db->getAttribute(PDO::ATTR_DRIVER_NAME)==='mysql'?' FOR UPDATE':'');$q=$this->db->prepare($sql);$q->execute([$id]);$o=$q->fetch();if(!$o)throw new RuntimeException('Oportunidade não encontrada.');return $o;}
}
