CREATE TABLE users (id CHAR(32) PRIMARY KEY, name VARCHAR(120) NOT NULL, email VARCHAR(190) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL, role ENUM('admin','manager','sdr','broker') NOT NULL, active TINYINT(1) NOT NULL DEFAULT 1, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE auth_tokens (id CHAR(32) PRIMARY KEY, user_id CHAR(32) NOT NULL, token_hash CHAR(64) NOT NULL UNIQUE, expires_at DATETIME NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE lead_sources (id CHAR(32) PRIMARY KEY, code VARCHAR(50) NOT NULL UNIQUE, name VARCHAR(100) NOT NULL, connector_status ENUM('local','awaiting_credentials','active') NOT NULL DEFAULT 'awaiting_credentials', requirements TEXT NULL);
CREATE TABLE contacts (id CHAR(32) PRIMARY KEY, name VARCHAR(150) NOT NULL, email VARCHAR(190) NULL, phone VARCHAR(30) NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX(email), INDEX(phone));
CREATE TABLE opportunities (id CHAR(32) PRIMARY KEY, contact_id CHAR(32) NOT NULL, source_id CHAR(32) NOT NULL, external_id VARCHAR(190) NULL, interest_type ENUM('purchase','rental') NOT NULL, region VARCHAR(150) NULL, min_value DECIMAL(13,2) NULL, max_value DECIMAL(13,2) NULL, property_interest TEXT NULL, stage ENUM('qualification','service','visit','proposal','negotiation','won','lost','nurturing') NOT NULL DEFAULT 'qualification', sdr_id CHAR(32) NULL, broker_id CHAR(32) NULL, loss_reason VARCHAR(255) NULL, first_service_at DATETIME NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY(contact_id) REFERENCES contacts(id), FOREIGN KEY(source_id) REFERENCES lead_sources(id), FOREIGN KEY(sdr_id) REFERENCES users(id), FOREIGN KEY(broker_id) REFERENCES users(id), UNIQUE KEY(source_id,external_id));
CREATE TABLE interactions (id CHAR(32) PRIMARY KEY, opportunity_id CHAR(32) NOT NULL, user_id CHAR(32) NULL, type VARCHAR(50) NOT NULL, description TEXT NOT NULL, metadata JSON NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(opportunity_id) REFERENCES opportunities(id) ON DELETE CASCADE, FOREIGN KEY(user_id) REFERENCES users(id));
CREATE TABLE tasks (id CHAR(32) PRIMARY KEY, opportunity_id CHAR(32) NOT NULL, assigned_to CHAR(32) NOT NULL, title VARCHAR(180) NOT NULL, due_at DATETIME NOT NULL, status ENUM('pending','done','cancelled') NOT NULL DEFAULT 'pending', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(opportunity_id) REFERENCES opportunities(id) ON DELETE CASCADE, FOREIGN KEY(assigned_to) REFERENCES users(id));
CREATE TABLE integration_events (id CHAR(32) PRIMARY KEY, source_id CHAR(32) NOT NULL, external_id VARCHAR(190) NULL, payload JSON NOT NULL, payload_hash CHAR(64) NOT NULL, status ENUM('received','processed','rejected','duplicate') NOT NULL, result_message VARCHAR(255) NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, processed_at DATETIME NULL, FOREIGN KEY(source_id) REFERENCES lead_sources(id), INDEX(payload_hash));

