ALTER TABLE lead_sources MODIFY connector_status ENUM('not_configured','awaiting_credentials','ready_for_test','connected','error','local') NOT NULL DEFAULT 'awaiting_credentials';
CREATE TABLE integration_connectors (id CHAR(32) PRIMARY KEY,code VARCHAR(60) NOT NULL UNIQUE,name VARCHAR(120) NOT NULL,purpose TEXT NOT NULL,status ENUM('not_configured','awaiting_credentials','ready_for_test','connected','error','local') NOT NULL DEFAULT 'not_configured',implementation_status ENUM('contract_only','implemented','simulated','real_validated') NOT NULL DEFAULT 'contract_only',provider VARCHAR(80) NULL,config JSON NULL,secret_ciphertext TEXT NULL,requirements TEXT NOT NULL,last_event_at DATETIME NULL,last_test_at DATETIME NULL,last_test_result VARCHAR(500) NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE integration_logs (id CHAR(32) PRIMARY KEY,connector_id CHAR(32) NOT NULL,level ENUM('info','warning','error') NOT NULL,message VARCHAR(500) NOT NULL,context JSON NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(connector_id) REFERENCES integration_connectors(id) ON DELETE CASCADE,INDEX(connector_id,created_at));
CREATE TABLE automation_flows (id CHAR(32) PRIMARY KEY,name VARCHAR(150) NOT NULL,status ENUM('draft','published','inactive') NOT NULL DEFAULT 'draft',draft_version_id CHAR(32) NULL,published_version_id CHAR(32) NULL,created_by CHAR(32) NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,FOREIGN KEY(created_by) REFERENCES users(id));
CREATE TABLE flow_versions (id CHAR(32) PRIMARY KEY,flow_id CHAR(32) NOT NULL,version_number INT NOT NULL,graph JSON NOT NULL,validation_errors JSON NULL,created_by CHAR(32) NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(flow_id) REFERENCES automation_flows(id) ON DELETE CASCADE,FOREIGN KEY(created_by) REFERENCES users(id),UNIQUE(flow_id,version_number));
ALTER TABLE automation_flows ADD FOREIGN KEY(draft_version_id) REFERENCES flow_versions(id),ADD FOREIGN KEY(published_version_id) REFERENCES flow_versions(id);
CREATE TABLE conversations (id CHAR(32) PRIMARY KEY,provider VARCHAR(50) NOT NULL,external_id VARCHAR(190) NOT NULL,phone VARCHAR(30) NULL,contact_id CHAR(32) NULL,opportunity_id CHAR(32) NULL,flow_version_id CHAR(32) NULL,current_node_id VARCHAR(80) NULL,state JSON NULL,automation_paused TINYINT(1) NOT NULL DEFAULT 0,status ENUM('active','waiting','human','closed','error') NOT NULL DEFAULT 'active',last_error TEXT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,FOREIGN KEY(contact_id) REFERENCES contacts(id),FOREIGN KEY(opportunity_id) REFERENCES opportunities(id),FOREIGN KEY(flow_version_id) REFERENCES flow_versions(id),UNIQUE(provider,external_id));
CREATE TABLE conversation_messages (id CHAR(32) PRIMARY KEY,conversation_id CHAR(32) NOT NULL,provider VARCHAR(50) NOT NULL,external_message_id VARCHAR(190) NOT NULL,direction ENUM('in','out') NOT NULL,body TEXT NOT NULL,block_id VARCHAR(80) NULL,status ENUM('received','sent','simulated','failed') NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(conversation_id) REFERENCES conversations(id) ON DELETE CASCADE,UNIQUE(provider,external_message_id));
INSERT INTO integration_connectors(id,code,name,purpose,status,implementation_status,provider,config,requirements) VALUES
('50000000000000000000000000000001','whatsapp_simulator','WhatsApp — simulador local','Testar conversas e fluxos sem número ou envio real.','local','simulated','simulator',JSON_OBJECT('real_messages',false),'Nenhum acesso externo necessário.'),
('50000000000000000000000000000002','whatsapp_pam','WhatsApp Web — PAM não oficial','Receber e enviar textos por sessão WhatsApp Web isolada.','awaiting_credentials','implemented','pam',JSON_OBJECT('session_path','fora da pasta pública'),'PAM 1.x, PHP compatível com PAM, Chrome/Chromium e leitura autorizada de QR por administrador.'),
('50000000000000000000000000000003','whatsapp_meta','WhatsApp Business Platform — Meta oficial','Mensagens oficiais e webhooks da Meta.','awaiting_credentials','contract_only','meta',JSON_OBJECT(),'Meta Business, WABA, número, app, token, segredo e verificação do webhook.'),
('50000000000000000000000000000004','olx','OLX/Canal Pro','Receber leads de anúncios e preservar o evento original.','awaiting_credentials','implemented','olx',JSON_OBJECT('public_docs',true),'Conta/plano elegível, homologação OLX, client_id, client_secret, OAuth e URL pública HTTPS.'),
('50000000000000000000000000000005','quintoandar','QuintoAndar','Receber leads quando houver contrato de integração disponível.','awaiting_credentials','contract_only',NULL,JSON_OBJECT(),'Documentação privada, contrato comercial, credenciais e payload oficial.'),
('50000000000000000000000000000006','site','Site e formulários','Captar formulários próprios via webhook autenticado.','ready_for_test','simulated','webhook',JSON_OBJECT(),'URL do site, campos do formulário e segredo compartilhado.'),
('50000000000000000000000000000007','email','E-mail corporativo','Ler leads por IMAP e preparar respostas via SMTP.','awaiting_credentials','contract_only','imap_smtp',JSON_OBJECT('imap_port',993,'smtp_port',587),'Host IMAP/SMTP, portas, TLS, usuário e senha de app/OAuth.'),
('50000000000000000000000000000008','social','Redes sociais','Normalizar leads recebidos de plataformas sociais.','awaiting_credentials','contract_only',NULL,JSON_OBJECT(),'Plataformas escolhidas, contas comerciais, apps, permissões e documentação.'),
('50000000000000000000000000000009','voip','Telefonia VoIP','Registrar chamadas e eventos do provedor.','awaiting_credentials','contract_only',NULL,JSON_OBJECT(),'Provedor, documentação, conta SIP/API, webhooks e política de gravação.'),
('50000000000000000000000000000010','site_chat','Chat do site','Receber conversas do widget e transferir para humano.','ready_for_test','simulated','simulator',JSON_OBJECT(),'Domínio autorizado e definição do widget.'),
('50000000000000000000000000000011','power_bi','Power BI','Disponibilizar indicadores gerenciais para modelo semântico.','awaiting_credentials','contract_only','power_bi',JSON_OBJECT(),'Tenant Entra ID, app, client_id, segredo/certificado, workspace e semantic model.');
