ALTER TABLE properties
 ADD listing_status ENUM('draft','pending_review','approved','rejected','archived') NOT NULL DEFAULT 'approved',
 ADD created_by CHAR(32) NULL,
 ADD submitted_at DATETIME NULL,
 ADD reviewed_by CHAR(32) NULL,
 ADD reviewed_at DATETIME NULL,
 ADD review_notes TEXT NULL,
 ADD description TEXT NULL,
 ADD rental_price DECIMAL(13,2) NULL,
 ADD condo_fee DECIMAL(13,2) NULL,
 ADD iptu_yearly DECIMAL(13,2) NULL,
 ADD area_total DECIMAL(10,2) NULL,
 ADD area_built DECIMAL(10,2) NULL,
 ADD bedrooms TINYINT UNSIGNED NULL,
 ADD suites TINYINT UNSIGNED NULL,
 ADD bathrooms TINYINT UNSIGNED NULL,
 ADD parking_spaces TINYINT UNSIGNED NULL,
 ADD floor_number SMALLINT NULL,
 ADD year_built SMALLINT NULL,
 ADD furnished ENUM('no','semi','yes') NULL,
 ADD accepts_pets TINYINT(1) NULL,
 ADD accepts_financing TINYINT(1) NULL,
 ADD accepts_exchange TINYINT(1) NULL,
 ADD features JSON NULL,
 ADD condo_features JSON NULL,
 ADD zip_code VARCHAR(9) NULL,
 ADD street VARCHAR(180) NULL,
 ADD street_number VARCHAR(20) NULL,
 ADD complement VARCHAR(80) NULL,
 ADD neighborhood VARCHAR(120) NULL,
 ADD city VARCHAR(120) NULL,
 ADD state CHAR(2) NULL,
 ADD condo_name VARCHAR(150) NULL,
 ADD show_full_address TINYINT(1) NOT NULL DEFAULT 0,
 ADD owner_name VARCHAR(150) NULL,
 ADD owner_document VARCHAR(20) NULL,
 ADD owner_phone VARCHAR(30) NULL,
 ADD owner_email VARCHAR(190) NULL,
 ADD registry_number VARCHAR(60) NULL,
 ADD registry_office VARCHAR(150) NULL,
 ADD iptu_number VARCHAR(60) NULL,
 ADD keys_location VARCHAR(180) NULL,
 ADD exclusive_listing TINYINT(1) NOT NULL DEFAULT 0,
 ADD commission_percent DECIMAL(5,2) NULL,
 ADD available_from DATE NULL,
 ADD FOREIGN KEY(created_by) REFERENCES users(id),
 ADD FOREIGN KEY(reviewed_by) REFERENCES users(id),
 ADD INDEX idx_listing(listing_status,created_at),
 ADD INDEX idx_creator(created_by,listing_status);
ALTER TABLE properties ALTER listing_status SET DEFAULT 'draft', MODIFY price DECIMAL(13,2) NULL;
ALTER TABLE property_photos ADD category VARCHAR(40) NOT NULL DEFAULT 'other', ADD slot VARCHAR(60) NOT NULL DEFAULT 'other', ADD caption VARCHAR(160) NULL, ADD width INT NULL, ADD height INT NULL, ADD uploaded_by CHAR(32) NULL, ADD FOREIGN KEY(uploaded_by) REFERENCES users(id), ADD INDEX idx_slot(property_id,slot);
CREATE TABLE property_review_events (id CHAR(32) PRIMARY KEY,property_id CHAR(32) NOT NULL,user_id CHAR(32) NOT NULL,action ENUM('created','submitted','approved','rejected','archived','edited_after_approval') NOT NULL,notes TEXT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(property_id) REFERENCES properties(id) ON DELETE CASCADE,FOREIGN KEY(user_id) REFERENCES users(id),INDEX(property_id,created_at));
