ALTER TABLE users MODIFY role ENUM('admin','manager','sdr','broker','analyst') NOT NULL;
CREATE TABLE credit_applications (
 id CHAR(32) PRIMARY KEY,
 code VARCHAR(20) NOT NULL UNIQUE,
 opportunity_id CHAR(32) NOT NULL,
 property_id CHAR(32) NOT NULL,
 broker_id CHAR(32) NOT NULL,
 analyst_id CHAR(32) NULL,
 business_type ENUM('purchase','rental') NOT NULL,
 payment_method ENUM('cash','financing','down_payment_financing','rental') NOT NULL,
 offer_value DECIMAL(13,2) NULL,
 down_payment DECIMAL(13,2) NULL,
 fgts_value DECIMAL(13,2) NULL,
 financing_value DECIMAL(13,2) NULL,
 financing_term_months SMALLINT NULL,
 bank_preference VARCHAR(80) NULL,
 rent_value DECIMAL(13,2) NULL,
 guarantee_type ENUM('deposit','guarantor','insurance','capitalization','none') NULL,
 lease_months SMALLINT NULL,
 move_in_date DATE NULL,
 applicant_name VARCHAR(150) NULL,
 household_income DECIMAL(13,2) NULL,
 personal_data TEXT NULL COMMENT 'JSON cifrado (sodium secretbox): proponente, cônjuge/compositor e fiador',
 notes TEXT NULL,
 consent_at DATETIME NULL,
 status ENUM('draft','submitted','in_analysis','pending_docs','approved','approved_conditions','rejected','cancelled') NOT NULL DEFAULT 'draft',
 decision_notes TEXT NULL,
 approved_value DECIMAL(13,2) NULL,
 approved_conditions TEXT NULL,
 submitted_at DATETIME NULL,
 decided_at DATETIME NULL,
 decided_by CHAR(32) NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY(opportunity_id) REFERENCES opportunities(id),
 FOREIGN KEY(property_id) REFERENCES properties(id),
 FOREIGN KEY(broker_id) REFERENCES users(id),
 FOREIGN KEY(analyst_id) REFERENCES users(id),
 FOREIGN KEY(decided_by) REFERENCES users(id),
 INDEX(status,submitted_at),
 INDEX(broker_id,status),
 INDEX(analyst_id,status)
);
CREATE TABLE credit_events (id CHAR(32) PRIMARY KEY,application_id CHAR(32) NOT NULL,user_id CHAR(32) NOT NULL,action VARCHAR(40) NOT NULL,notes TEXT NULL,created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6),FOREIGN KEY(application_id) REFERENCES credit_applications(id) ON DELETE CASCADE,FOREIGN KEY(user_id) REFERENCES users(id),INDEX(application_id,created_at));
ALTER TABLE documents MODIFY entity_type ENUM('contact','opportunity','proposal','contract','credit_application') NOT NULL, ADD label VARCHAR(80) NULL;
