-- Origens de lead: dados estruturais (antes só criados pelo seed.php).
-- A aplicação localiza cada origem pelo "code" (UNIQUE): local, site e whatsapp são usados diretamente no código;
-- olx, quintoandar, email, social e partner pela importação CSV e pelos conectores de integração.
-- Idempotente: insere apenas os códigos que ainda não existem; nunca altera nome, status ou requisitos já gravados.
INSERT INTO lead_sources(id,code,name,connector_status,requirements) SELECT REPLACE(UUID(),'-',''),'local','Entrada local','local','Token WEBHOOK_TOKEN' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM lead_sources WHERE code='local');
INSERT INTO lead_sources(id,code,name,connector_status,requirements) SELECT REPLACE(UUID(),'-',''),'site','Site e formulários','awaiting_credentials','URL/formato do formulário e segredo de assinatura' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM lead_sources WHERE code='site');
INSERT INTO lead_sources(id,code,name,connector_status,requirements) SELECT REPLACE(UUID(),'-',''),'olx','OLX/Canal Pro','awaiting_credentials','Documentação da API, credenciais e formato/assinatura do webhook' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM lead_sources WHERE code='olx');
INSERT INTO lead_sources(id,code,name,connector_status,requirements) SELECT REPLACE(UUID(),'-',''),'quintoandar','QuintoAndar','awaiting_credentials','Documentação, credenciais e permissões da conta' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM lead_sources WHERE code='quintoandar');
INSERT INTO lead_sources(id,code,name,connector_status,requirements) SELECT REPLACE(UUID(),'-',''),'whatsapp','WhatsApp oficial','awaiting_credentials','Meta Business, WABA, número, token e segredo do app' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM lead_sources WHERE code='whatsapp');
INSERT INTO lead_sources(id,code,name,connector_status,requirements) SELECT REPLACE(UUID(),'-',''),'email','E-mail','awaiting_credentials','Provedor, OAuth/IMAP e regras de consentimento' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM lead_sources WHERE code='email');
INSERT INTO lead_sources(id,code,name,connector_status,requirements) SELECT REPLACE(UUID(),'-',''),'social','Redes sociais','awaiting_credentials','Plataformas, contas comerciais, apps e permissões' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM lead_sources WHERE code='social');
INSERT INTO lead_sources(id,code,name,connector_status,requirements) SELECT REPLACE(UUID(),'-',''),'partner','Outros portais/parceiros','awaiting_credentials','Documentação e credenciais de cada parceiro' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM lead_sources WHERE code='partner');
